#pragma once
// GENERATED by compiler/tools/gen_ast.py -- DO NOT EDIT.
// Source: CPython 3.14.7 (schema v1)
//
// Regenerate when the target CPython changes. A new node kind will
// break every non-exhaustive std::visit, which is CHARTER I4 working
// as designed -- fix the arms, never add a generic `auto` fallback.
#include "pyc/ast/support.hpp"

namespace pyc::ast {

inline constexpr const char* kTargetPython = "3.14.7";

// --- forward declarations ---
struct Add;
struct And;
struct AnnAssign;
struct Assert;
struct Assign;
struct AsyncFor;
struct AsyncFunctionDef;
struct AsyncWith;
struct Attribute;
struct AugAssign;
struct AugLoad;
struct AugStore;
struct Await;
struct BinOp;
struct BitAnd;
struct BitOr;
struct BitXor;
struct BoolOp;
struct Break;
struct Call;
struct ClassDef;
struct Compare;
struct Constant;
struct Continue;
struct Del;
struct Delete;
struct Dict;
struct DictComp;
struct Div;
struct Eq;
struct ExceptHandler;
struct Expr;
struct Expression;
struct FloorDiv;
struct For;
struct FormattedValue;
struct FunctionDef;
struct FunctionType;
struct GeneratorExp;
struct Global;
struct Gt;
struct GtE;
struct If;
struct IfExp;
struct Import;
struct ImportFrom;
struct In;
struct Interactive;
struct Interpolation;
struct Invert;
struct Is;
struct IsNot;
struct JoinedStr;
struct LShift;
struct Lambda;
struct List;
struct ListComp;
struct Load;
struct Lt;
struct LtE;
struct MatMult;
struct Match;
struct MatchAs;
struct MatchClass;
struct MatchMapping;
struct MatchOr;
struct MatchSequence;
struct MatchSingleton;
struct MatchStar;
struct MatchValue;
struct Mod;
struct Module;
struct Mult;
struct Name;
struct NamedExpr;
struct Nonlocal;
struct Not;
struct NotEq;
struct NotIn;
struct Or;
struct Param;
struct ParamSpec;
struct Pass;
struct Pow;
struct RShift;
struct Raise;
struct Return;
struct Set;
struct SetComp;
struct Slice;
struct Starred;
struct Store;
struct Sub;
struct Subscript;
struct Suite;
struct TemplateStr;
struct Try;
struct TryStar;
struct Tuple;
struct TypeAlias;
struct TypeIgnore;
struct TypeVar;
struct TypeVarTuple;
struct UAdd;
struct USub;
struct UnaryOp;
struct While;
struct With;
struct Yield;
struct YieldFrom;
struct alias;
struct arg;
struct arguments;
struct boolop;
struct cmpop;
struct comprehension;
struct excepthandler;
struct expr;
struct expr_context;
struct keyword;
struct match_case;
struct mod;
struct operator_;
struct pattern;
struct stmt;
struct type_ignore;
struct type_param;
struct unaryop;
struct withitem;

// --- field-free sums (held by value) ---
struct And {};
struct Or {};
struct boolop { std::variant<And, Or> v; };
struct Eq {};
struct Gt {};
struct GtE {};
struct In {};
struct Is {};
struct IsNot {};
struct Lt {};
struct LtE {};
struct NotEq {};
struct NotIn {};
struct cmpop { std::variant<Eq, Gt, GtE, In, Is, IsNot, Lt, LtE, NotEq, NotIn> v; };
struct AugLoad {};
struct AugStore {};
struct Del {};
struct Load {};
struct Param {};
struct Store {};
struct expr_context { std::variant<AugLoad, AugStore, Del, Load, Param, Store> v; };
struct Add {};
struct BitAnd {};
struct BitOr {};
struct BitXor {};
struct Div {};
struct FloorDiv {};
struct LShift {};
struct MatMult {};
struct Mod {};
struct Mult {};
struct Pow {};
struct RShift {};
struct Sub {};
struct operator_ { std::variant<Add, BitAnd, BitOr, BitXor, Div, FloorDiv, LShift, MatMult, Mod, Mult, Pow, RShift, Sub> v; };
struct Invert {};
struct Not {};
struct UAdd {};
struct USub {};
struct unaryop { std::variant<Invert, Not, UAdd, USub> v; };

// --- nodes ---
struct AnnAssign {
    Box<::pyc::ast::expr> target;
    Box<::pyc::ast::expr> annotation;
    std::optional<Box<::pyc::ast::expr>> value;
    std::int64_t simple;
    SourceLoc loc;
};
struct Assert {
    Box<::pyc::ast::expr> test;
    std::optional<Box<::pyc::ast::expr>> msg;
    SourceLoc loc;
};
struct Assign {
    std::vector<::pyc::ast::expr> targets;
    Box<::pyc::ast::expr> value;
    std::optional<std::string> type_comment;
    SourceLoc loc;
};
struct AsyncFor {
    Box<::pyc::ast::expr> target;
    Box<::pyc::ast::expr> iter;
    std::vector<::pyc::ast::stmt> body;
    std::vector<::pyc::ast::stmt> orelse;
    std::optional<std::string> type_comment;
    SourceLoc loc;
};
struct AsyncFunctionDef {
    std::string name;
    Box<::pyc::ast::arguments> args;
    std::vector<::pyc::ast::stmt> body;
    std::vector<::pyc::ast::expr> decorator_list;
    std::optional<Box<::pyc::ast::expr>> returns;
    std::optional<std::string> type_comment;
    std::vector<::pyc::ast::type_param> type_params;
    SourceLoc loc;
};
struct AsyncWith {
    std::vector<::pyc::ast::withitem> items;
    std::vector<::pyc::ast::stmt> body;
    std::optional<std::string> type_comment;
    SourceLoc loc;
};
struct Attribute {
    Box<::pyc::ast::expr> value;
    std::string attr;
    ::pyc::ast::expr_context ctx;
    SourceLoc loc;
};
struct AugAssign {
    Box<::pyc::ast::expr> target;
    ::pyc::ast::operator_ op;
    Box<::pyc::ast::expr> value;
    SourceLoc loc;
};
struct Await {
    Box<::pyc::ast::expr> value;
    SourceLoc loc;
};
struct BinOp {
    Box<::pyc::ast::expr> left;
    ::pyc::ast::operator_ op;
    Box<::pyc::ast::expr> right;
    SourceLoc loc;
};
struct BoolOp {
    ::pyc::ast::boolop op;
    std::vector<::pyc::ast::expr> values;
    SourceLoc loc;
};
struct Break {
    SourceLoc loc;
};
struct Call {
    Box<::pyc::ast::expr> func;
    std::vector<::pyc::ast::expr> args;
    std::vector<::pyc::ast::keyword> keywords;
    SourceLoc loc;
};
struct ClassDef {
    std::string name;
    std::vector<::pyc::ast::expr> bases;
    std::vector<::pyc::ast::keyword> keywords;
    std::vector<::pyc::ast::stmt> body;
    std::vector<::pyc::ast::expr> decorator_list;
    std::vector<::pyc::ast::type_param> type_params;
    SourceLoc loc;
};
struct Compare {
    Box<::pyc::ast::expr> left;
    std::vector<::pyc::ast::cmpop> ops;
    std::vector<::pyc::ast::expr> comparators;
    SourceLoc loc;
};
struct Constant {
    ConstantValue value;
    std::optional<std::string> kind;
    SourceLoc loc;
};
struct Continue {
    SourceLoc loc;
};
struct Delete {
    std::vector<::pyc::ast::expr> targets;
    SourceLoc loc;
};
struct Dict {
    std::vector<std::optional<Box<::pyc::ast::expr>>> keys;
    std::vector<::pyc::ast::expr> values;
    SourceLoc loc;
};
struct DictComp {
    Box<::pyc::ast::expr> key;
    Box<::pyc::ast::expr> value;
    std::vector<::pyc::ast::comprehension> generators;
    SourceLoc loc;
};
struct ExceptHandler {
    std::optional<Box<::pyc::ast::expr>> type;
    std::optional<std::string> name;
    std::vector<::pyc::ast::stmt> body;
    SourceLoc loc;
};
struct Expr {
    Box<::pyc::ast::expr> value;
    SourceLoc loc;
};
struct Expression {
    Box<::pyc::ast::expr> body;
};
struct For {
    Box<::pyc::ast::expr> target;
    Box<::pyc::ast::expr> iter;
    std::vector<::pyc::ast::stmt> body;
    std::vector<::pyc::ast::stmt> orelse;
    std::optional<std::string> type_comment;
    SourceLoc loc;
};
struct FormattedValue {
    Box<::pyc::ast::expr> value;
    std::int64_t conversion;
    std::optional<Box<::pyc::ast::expr>> format_spec;
    SourceLoc loc;
};
struct FunctionDef {
    std::string name;
    Box<::pyc::ast::arguments> args;
    std::vector<::pyc::ast::stmt> body;
    std::vector<::pyc::ast::expr> decorator_list;
    std::optional<Box<::pyc::ast::expr>> returns;
    std::optional<std::string> type_comment;
    std::vector<::pyc::ast::type_param> type_params;
    SourceLoc loc;
};
struct FunctionType {
    std::vector<::pyc::ast::expr> argtypes;
    Box<::pyc::ast::expr> returns;
};
struct GeneratorExp {
    Box<::pyc::ast::expr> elt;
    std::vector<::pyc::ast::comprehension> generators;
    SourceLoc loc;
};
struct Global {
    std::vector<std::string> names;
    SourceLoc loc;
};
struct If {
    Box<::pyc::ast::expr> test;
    std::vector<::pyc::ast::stmt> body;
    std::vector<::pyc::ast::stmt> orelse;
    SourceLoc loc;
};
struct IfExp {
    Box<::pyc::ast::expr> test;
    Box<::pyc::ast::expr> body;
    Box<::pyc::ast::expr> orelse;
    SourceLoc loc;
};
struct Import {
    std::vector<::pyc::ast::alias> names;
    SourceLoc loc;
};
struct ImportFrom {
    std::optional<std::string> module;
    std::vector<::pyc::ast::alias> names;
    std::optional<std::int64_t> level;
    SourceLoc loc;
};
struct Interactive {
    std::vector<::pyc::ast::stmt> body;
};
struct Interpolation {
    Box<::pyc::ast::expr> value;
    std::string str;
    std::int64_t conversion;
    std::optional<Box<::pyc::ast::expr>> format_spec;
    SourceLoc loc;
};
struct JoinedStr {
    std::vector<::pyc::ast::expr> values;
    SourceLoc loc;
};
struct Lambda {
    Box<::pyc::ast::arguments> args;
    Box<::pyc::ast::expr> body;
    SourceLoc loc;
};
struct List {
    std::vector<::pyc::ast::expr> elts;
    ::pyc::ast::expr_context ctx;
    SourceLoc loc;
};
struct ListComp {
    Box<::pyc::ast::expr> elt;
    std::vector<::pyc::ast::comprehension> generators;
    SourceLoc loc;
};
struct Match {
    Box<::pyc::ast::expr> subject;
    std::vector<::pyc::ast::match_case> cases;
    SourceLoc loc;
};
struct MatchAs {
    std::optional<Box<::pyc::ast::pattern>> pattern;
    std::optional<std::string> name;
    SourceLoc loc;
};
struct MatchClass {
    Box<::pyc::ast::expr> cls;
    std::vector<::pyc::ast::pattern> patterns;
    std::vector<std::string> kwd_attrs;
    std::vector<::pyc::ast::pattern> kwd_patterns;
    SourceLoc loc;
};
struct MatchMapping {
    std::vector<::pyc::ast::expr> keys;
    std::vector<::pyc::ast::pattern> patterns;
    std::optional<std::string> rest;
    SourceLoc loc;
};
struct MatchOr {
    std::vector<::pyc::ast::pattern> patterns;
    SourceLoc loc;
};
struct MatchSequence {
    std::vector<::pyc::ast::pattern> patterns;
    SourceLoc loc;
};
struct MatchSingleton {
    ConstantValue value;
    SourceLoc loc;
};
struct MatchStar {
    std::optional<std::string> name;
    SourceLoc loc;
};
struct MatchValue {
    Box<::pyc::ast::expr> value;
    SourceLoc loc;
};
struct Module {
    std::vector<::pyc::ast::stmt> body;
    std::vector<::pyc::ast::type_ignore> type_ignores;
};
struct Name {
    std::string id;
    ::pyc::ast::expr_context ctx;
    SourceLoc loc;
};
struct NamedExpr {
    Box<::pyc::ast::expr> target;
    Box<::pyc::ast::expr> value;
    SourceLoc loc;
};
struct Nonlocal {
    std::vector<std::string> names;
    SourceLoc loc;
};
struct ParamSpec {
    std::string name;
    std::optional<Box<::pyc::ast::expr>> default_value;
    SourceLoc loc;
};
struct Pass {
    SourceLoc loc;
};
struct Raise {
    std::optional<Box<::pyc::ast::expr>> exc;
    std::optional<Box<::pyc::ast::expr>> cause;
    SourceLoc loc;
};
struct Return {
    std::optional<Box<::pyc::ast::expr>> value;
    SourceLoc loc;
};
struct Set {
    std::vector<::pyc::ast::expr> elts;
    SourceLoc loc;
};
struct SetComp {
    Box<::pyc::ast::expr> elt;
    std::vector<::pyc::ast::comprehension> generators;
    SourceLoc loc;
};
struct Slice {
    std::optional<Box<::pyc::ast::expr>> lower;
    std::optional<Box<::pyc::ast::expr>> upper;
    std::optional<Box<::pyc::ast::expr>> step;
    SourceLoc loc;
};
struct Starred {
    Box<::pyc::ast::expr> value;
    ::pyc::ast::expr_context ctx;
    SourceLoc loc;
};
struct Subscript {
    Box<::pyc::ast::expr> value;
    Box<::pyc::ast::expr> slice;
    ::pyc::ast::expr_context ctx;
    SourceLoc loc;
};
struct Suite {
};
struct TemplateStr {
    std::vector<::pyc::ast::expr> values;
    SourceLoc loc;
};
struct Try {
    std::vector<::pyc::ast::stmt> body;
    std::vector<::pyc::ast::excepthandler> handlers;
    std::vector<::pyc::ast::stmt> orelse;
    std::vector<::pyc::ast::stmt> finalbody;
    SourceLoc loc;
};
struct TryStar {
    std::vector<::pyc::ast::stmt> body;
    std::vector<::pyc::ast::excepthandler> handlers;
    std::vector<::pyc::ast::stmt> orelse;
    std::vector<::pyc::ast::stmt> finalbody;
    SourceLoc loc;
};
struct Tuple {
    std::vector<::pyc::ast::expr> elts;
    ::pyc::ast::expr_context ctx;
    SourceLoc loc;
};
struct TypeAlias {
    Box<::pyc::ast::expr> name;
    std::vector<::pyc::ast::type_param> type_params;
    Box<::pyc::ast::expr> value;
    SourceLoc loc;
};
struct TypeIgnore {
    std::int64_t lineno;
    std::string tag;
};
struct TypeVar {
    std::string name;
    std::optional<Box<::pyc::ast::expr>> bound;
    std::optional<Box<::pyc::ast::expr>> default_value;
    SourceLoc loc;
};
struct TypeVarTuple {
    std::string name;
    std::optional<Box<::pyc::ast::expr>> default_value;
    SourceLoc loc;
};
struct UnaryOp {
    ::pyc::ast::unaryop op;
    Box<::pyc::ast::expr> operand;
    SourceLoc loc;
};
struct While {
    Box<::pyc::ast::expr> test;
    std::vector<::pyc::ast::stmt> body;
    std::vector<::pyc::ast::stmt> orelse;
    SourceLoc loc;
};
struct With {
    std::vector<::pyc::ast::withitem> items;
    std::vector<::pyc::ast::stmt> body;
    std::optional<std::string> type_comment;
    SourceLoc loc;
};
struct Yield {
    std::optional<Box<::pyc::ast::expr>> value;
    SourceLoc loc;
};
struct YieldFrom {
    Box<::pyc::ast::expr> value;
    SourceLoc loc;
};
struct alias {
    std::string name;
    std::optional<std::string> asname;
    SourceLoc loc;
};
struct arg {
    std::string arg;
    std::optional<Box<::pyc::ast::expr>> annotation;
    std::optional<std::string> type_comment;
    SourceLoc loc;
};
struct arguments {
    std::vector<::pyc::ast::arg> posonlyargs;
    std::vector<::pyc::ast::arg> args;
    std::optional<Box<::pyc::ast::arg>> vararg;
    std::vector<::pyc::ast::arg> kwonlyargs;
    std::vector<std::optional<Box<::pyc::ast::expr>>> kw_defaults;
    std::optional<Box<::pyc::ast::arg>> kwarg;
    std::vector<::pyc::ast::expr> defaults;
};
struct comprehension {
    Box<::pyc::ast::expr> target;
    Box<::pyc::ast::expr> iter;
    std::vector<::pyc::ast::expr> ifs;
    std::int64_t is_async;
};
struct keyword {
    std::optional<std::string> arg;
    Box<::pyc::ast::expr> value;
    SourceLoc loc;
};
struct match_case {
    Box<::pyc::ast::pattern> pattern;
    std::optional<Box<::pyc::ast::expr>> guard;
    std::vector<::pyc::ast::stmt> body;
};
struct withitem {
    Box<::pyc::ast::expr> context_expr;
    std::optional<Box<::pyc::ast::expr>> optional_vars;
};

// --- sums ---
struct excepthandler {
    std::variant<ExceptHandler> v;
};
struct expr {
    std::variant<Attribute,
                 Await,
                 BinOp,
                 BoolOp,
                 Call,
                 Compare,
                 Constant,
                 Dict,
                 DictComp,
                 FormattedValue,
                 GeneratorExp,
                 IfExp,
                 Interpolation,
                 JoinedStr,
                 Lambda,
                 List,
                 ListComp,
                 Name,
                 NamedExpr,
                 Set,
                 SetComp,
                 Slice,
                 Starred,
                 Subscript,
                 TemplateStr,
                 Tuple,
                 UnaryOp,
                 Yield,
                 YieldFrom> v;
};
struct mod {
    std::variant<Expression,
                 FunctionType,
                 Interactive,
                 Module,
                 Suite> v;
};
struct pattern {
    std::variant<MatchAs,
                 MatchClass,
                 MatchMapping,
                 MatchOr,
                 MatchSequence,
                 MatchSingleton,
                 MatchStar,
                 MatchValue> v;
};
struct stmt {
    std::variant<AnnAssign,
                 Assert,
                 Assign,
                 AsyncFor,
                 AsyncFunctionDef,
                 AsyncWith,
                 AugAssign,
                 Break,
                 ClassDef,
                 Continue,
                 Delete,
                 Expr,
                 For,
                 FunctionDef,
                 Global,
                 If,
                 Import,
                 ImportFrom,
                 Match,
                 Nonlocal,
                 Pass,
                 Raise,
                 Return,
                 Try,
                 TryStar,
                 TypeAlias,
                 While,
                 With> v;
};
struct type_ignore {
    std::variant<TypeIgnore> v;
};
struct type_param {
    std::variant<ParamSpec,
                 TypeVar,
                 TypeVarTuple> v;
};

}  // namespace pyc::ast
