#pragma once
// GENERATED by compiler/tools/gen_ast.py -- DO NOT EDIT.
#include "pyc/ast/generated.hpp"

#include <string_view>

namespace pyc::ast {

struct WalkSink { virtual ~WalkSink() = default;
                  virtual void on(std::string_view kind) = 0; };

void walk(const Add& n, WalkSink& s);
void walk(const And& n, WalkSink& s);
void walk(const AnnAssign& n, WalkSink& s);
void walk(const Assert& n, WalkSink& s);
void walk(const Assign& n, WalkSink& s);
void walk(const AsyncFor& n, WalkSink& s);
void walk(const AsyncFunctionDef& n, WalkSink& s);
void walk(const AsyncWith& n, WalkSink& s);
void walk(const Attribute& n, WalkSink& s);
void walk(const AugAssign& n, WalkSink& s);
void walk(const AugLoad& n, WalkSink& s);
void walk(const AugStore& n, WalkSink& s);
void walk(const Await& n, WalkSink& s);
void walk(const BinOp& n, WalkSink& s);
void walk(const BitAnd& n, WalkSink& s);
void walk(const BitOr& n, WalkSink& s);
void walk(const BitXor& n, WalkSink& s);
void walk(const BoolOp& n, WalkSink& s);
void walk(const Break& n, WalkSink& s);
void walk(const Call& n, WalkSink& s);
void walk(const ClassDef& n, WalkSink& s);
void walk(const Compare& n, WalkSink& s);
void walk(const Constant& n, WalkSink& s);
void walk(const Continue& n, WalkSink& s);
void walk(const Del& n, WalkSink& s);
void walk(const Delete& n, WalkSink& s);
void walk(const Dict& n, WalkSink& s);
void walk(const DictComp& n, WalkSink& s);
void walk(const Div& n, WalkSink& s);
void walk(const Eq& n, WalkSink& s);
void walk(const ExceptHandler& n, WalkSink& s);
void walk(const Expr& n, WalkSink& s);
void walk(const Expression& n, WalkSink& s);
void walk(const FloorDiv& n, WalkSink& s);
void walk(const For& n, WalkSink& s);
void walk(const FormattedValue& n, WalkSink& s);
void walk(const FunctionDef& n, WalkSink& s);
void walk(const FunctionType& n, WalkSink& s);
void walk(const GeneratorExp& n, WalkSink& s);
void walk(const Global& n, WalkSink& s);
void walk(const Gt& n, WalkSink& s);
void walk(const GtE& n, WalkSink& s);
void walk(const If& n, WalkSink& s);
void walk(const IfExp& n, WalkSink& s);
void walk(const Import& n, WalkSink& s);
void walk(const ImportFrom& n, WalkSink& s);
void walk(const In& n, WalkSink& s);
void walk(const Interactive& n, WalkSink& s);
void walk(const Interpolation& n, WalkSink& s);
void walk(const Invert& n, WalkSink& s);
void walk(const Is& n, WalkSink& s);
void walk(const IsNot& n, WalkSink& s);
void walk(const JoinedStr& n, WalkSink& s);
void walk(const LShift& n, WalkSink& s);
void walk(const Lambda& n, WalkSink& s);
void walk(const List& n, WalkSink& s);
void walk(const ListComp& n, WalkSink& s);
void walk(const Load& n, WalkSink& s);
void walk(const Lt& n, WalkSink& s);
void walk(const LtE& n, WalkSink& s);
void walk(const MatMult& n, WalkSink& s);
void walk(const Match& n, WalkSink& s);
void walk(const MatchAs& n, WalkSink& s);
void walk(const MatchClass& n, WalkSink& s);
void walk(const MatchMapping& n, WalkSink& s);
void walk(const MatchOr& n, WalkSink& s);
void walk(const MatchSequence& n, WalkSink& s);
void walk(const MatchSingleton& n, WalkSink& s);
void walk(const MatchStar& n, WalkSink& s);
void walk(const MatchValue& n, WalkSink& s);
void walk(const Mod& n, WalkSink& s);
void walk(const Module& n, WalkSink& s);
void walk(const Mult& n, WalkSink& s);
void walk(const Name& n, WalkSink& s);
void walk(const NamedExpr& n, WalkSink& s);
void walk(const Nonlocal& n, WalkSink& s);
void walk(const Not& n, WalkSink& s);
void walk(const NotEq& n, WalkSink& s);
void walk(const NotIn& n, WalkSink& s);
void walk(const Or& n, WalkSink& s);
void walk(const Param& n, WalkSink& s);
void walk(const ParamSpec& n, WalkSink& s);
void walk(const Pass& n, WalkSink& s);
void walk(const Pow& n, WalkSink& s);
void walk(const RShift& n, WalkSink& s);
void walk(const Raise& n, WalkSink& s);
void walk(const Return& n, WalkSink& s);
void walk(const Set& n, WalkSink& s);
void walk(const SetComp& n, WalkSink& s);
void walk(const Slice& n, WalkSink& s);
void walk(const Starred& n, WalkSink& s);
void walk(const Store& n, WalkSink& s);
void walk(const Sub& n, WalkSink& s);
void walk(const Subscript& n, WalkSink& s);
void walk(const Suite& n, WalkSink& s);
void walk(const TemplateStr& n, WalkSink& s);
void walk(const Try& n, WalkSink& s);
void walk(const TryStar& n, WalkSink& s);
void walk(const Tuple& n, WalkSink& s);
void walk(const TypeAlias& n, WalkSink& s);
void walk(const TypeIgnore& n, WalkSink& s);
void walk(const TypeVar& n, WalkSink& s);
void walk(const TypeVarTuple& n, WalkSink& s);
void walk(const UAdd& n, WalkSink& s);
void walk(const USub& n, WalkSink& s);
void walk(const UnaryOp& n, WalkSink& s);
void walk(const While& n, WalkSink& s);
void walk(const With& n, WalkSink& s);
void walk(const Yield& n, WalkSink& s);
void walk(const YieldFrom& n, WalkSink& s);
void walk(const alias& n, WalkSink& s);
void walk(const arg& n, WalkSink& s);
void walk(const arguments& n, WalkSink& s);
void walk(const comprehension& n, WalkSink& s);
void walk(const excepthandler& n, WalkSink& s);
void walk(const expr& n, WalkSink& s);
void walk(const keyword& n, WalkSink& s);
void walk(const match_case& n, WalkSink& s);
void walk(const mod& n, WalkSink& s);
void walk(const pattern& n, WalkSink& s);
void walk(const stmt& n, WalkSink& s);
void walk(const type_ignore& n, WalkSink& s);
void walk(const type_param& n, WalkSink& s);
void walk(const withitem& n, WalkSink& s);

inline void walk(const AnnAssign& n, WalkSink& s) {
    s.on("AnnAssign");
    if (n.target) walk(*n.target, s);
    if (n.annotation) walk(*n.annotation, s);
    if (n.value && *n.value) walk(**n.value, s);
}
inline void walk(const Assert& n, WalkSink& s) {
    s.on("Assert");
    if (n.test) walk(*n.test, s);
    if (n.msg && *n.msg) walk(**n.msg, s);
}
inline void walk(const Assign& n, WalkSink& s) {
    s.on("Assign");
    for (const auto& x : n.targets) walk(x, s);
    if (n.value) walk(*n.value, s);
}
inline void walk(const AsyncFor& n, WalkSink& s) {
    s.on("AsyncFor");
    if (n.target) walk(*n.target, s);
    if (n.iter) walk(*n.iter, s);
    for (const auto& x : n.body) walk(x, s);
    for (const auto& x : n.orelse) walk(x, s);
}
inline void walk(const AsyncFunctionDef& n, WalkSink& s) {
    s.on("AsyncFunctionDef");
    if (n.args) walk(*n.args, s);
    for (const auto& x : n.body) walk(x, s);
    for (const auto& x : n.decorator_list) walk(x, s);
    if (n.returns && *n.returns) walk(**n.returns, s);
    for (const auto& x : n.type_params) walk(x, s);
}
inline void walk(const AsyncWith& n, WalkSink& s) {
    s.on("AsyncWith");
    for (const auto& x : n.items) walk(x, s);
    for (const auto& x : n.body) walk(x, s);
}
inline void walk(const Attribute& n, WalkSink& s) {
    s.on("Attribute");
    if (n.value) walk(*n.value, s);
}
inline void walk(const AugAssign& n, WalkSink& s) {
    s.on("AugAssign");
    if (n.target) walk(*n.target, s);
    if (n.value) walk(*n.value, s);
}
inline void walk(const Await& n, WalkSink& s) {
    s.on("Await");
    if (n.value) walk(*n.value, s);
}
inline void walk(const BinOp& n, WalkSink& s) {
    s.on("BinOp");
    if (n.left) walk(*n.left, s);
    if (n.right) walk(*n.right, s);
}
inline void walk(const BoolOp& n, WalkSink& s) {
    s.on("BoolOp");
    for (const auto& x : n.values) walk(x, s);
}
inline void walk(const Break& n, WalkSink& s) {
    s.on("Break");
}
inline void walk(const Call& n, WalkSink& s) {
    s.on("Call");
    if (n.func) walk(*n.func, s);
    for (const auto& x : n.args) walk(x, s);
    for (const auto& x : n.keywords) walk(x, s);
}
inline void walk(const ClassDef& n, WalkSink& s) {
    s.on("ClassDef");
    for (const auto& x : n.bases) walk(x, s);
    for (const auto& x : n.keywords) walk(x, s);
    for (const auto& x : n.body) walk(x, s);
    for (const auto& x : n.decorator_list) walk(x, s);
    for (const auto& x : n.type_params) walk(x, s);
}
inline void walk(const Compare& n, WalkSink& s) {
    s.on("Compare");
    if (n.left) walk(*n.left, s);
    for (const auto& x : n.comparators) walk(x, s);
}
inline void walk(const Constant& n, WalkSink& s) {
    s.on("Constant");
}
inline void walk(const Continue& n, WalkSink& s) {
    s.on("Continue");
}
inline void walk(const Delete& n, WalkSink& s) {
    s.on("Delete");
    for (const auto& x : n.targets) walk(x, s);
}
inline void walk(const Dict& n, WalkSink& s) {
    s.on("Dict");
    for (const auto& x : n.keys) if (x && *x) walk(**x, s);
    for (const auto& x : n.values) walk(x, s);
}
inline void walk(const DictComp& n, WalkSink& s) {
    s.on("DictComp");
    if (n.key) walk(*n.key, s);
    if (n.value) walk(*n.value, s);
    for (const auto& x : n.generators) walk(x, s);
}
inline void walk(const ExceptHandler& n, WalkSink& s) {
    s.on("ExceptHandler");
    if (n.type && *n.type) walk(**n.type, s);
    for (const auto& x : n.body) walk(x, s);
}
inline void walk(const Expr& n, WalkSink& s) {
    s.on("Expr");
    if (n.value) walk(*n.value, s);
}
inline void walk(const Expression& n, WalkSink& s) {
    s.on("Expression");
    if (n.body) walk(*n.body, s);
}
inline void walk(const For& n, WalkSink& s) {
    s.on("For");
    if (n.target) walk(*n.target, s);
    if (n.iter) walk(*n.iter, s);
    for (const auto& x : n.body) walk(x, s);
    for (const auto& x : n.orelse) walk(x, s);
}
inline void walk(const FormattedValue& n, WalkSink& s) {
    s.on("FormattedValue");
    if (n.value) walk(*n.value, s);
    if (n.format_spec && *n.format_spec) walk(**n.format_spec, s);
}
inline void walk(const FunctionDef& n, WalkSink& s) {
    s.on("FunctionDef");
    if (n.args) walk(*n.args, s);
    for (const auto& x : n.body) walk(x, s);
    for (const auto& x : n.decorator_list) walk(x, s);
    if (n.returns && *n.returns) walk(**n.returns, s);
    for (const auto& x : n.type_params) walk(x, s);
}
inline void walk(const FunctionType& n, WalkSink& s) {
    s.on("FunctionType");
    for (const auto& x : n.argtypes) walk(x, s);
    if (n.returns) walk(*n.returns, s);
}
inline void walk(const GeneratorExp& n, WalkSink& s) {
    s.on("GeneratorExp");
    if (n.elt) walk(*n.elt, s);
    for (const auto& x : n.generators) walk(x, s);
}
inline void walk(const Global& n, WalkSink& s) {
    s.on("Global");
}
inline void walk(const If& n, WalkSink& s) {
    s.on("If");
    if (n.test) walk(*n.test, s);
    for (const auto& x : n.body) walk(x, s);
    for (const auto& x : n.orelse) walk(x, s);
}
inline void walk(const IfExp& n, WalkSink& s) {
    s.on("IfExp");
    if (n.test) walk(*n.test, s);
    if (n.body) walk(*n.body, s);
    if (n.orelse) walk(*n.orelse, s);
}
inline void walk(const Import& n, WalkSink& s) {
    s.on("Import");
    for (const auto& x : n.names) walk(x, s);
}
inline void walk(const ImportFrom& n, WalkSink& s) {
    s.on("ImportFrom");
    for (const auto& x : n.names) walk(x, s);
}
inline void walk(const Interactive& n, WalkSink& s) {
    s.on("Interactive");
    for (const auto& x : n.body) walk(x, s);
}
inline void walk(const Interpolation& n, WalkSink& s) {
    s.on("Interpolation");
    if (n.value) walk(*n.value, s);
    if (n.format_spec && *n.format_spec) walk(**n.format_spec, s);
}
inline void walk(const JoinedStr& n, WalkSink& s) {
    s.on("JoinedStr");
    for (const auto& x : n.values) walk(x, s);
}
inline void walk(const Lambda& n, WalkSink& s) {
    s.on("Lambda");
    if (n.args) walk(*n.args, s);
    if (n.body) walk(*n.body, s);
}
inline void walk(const List& n, WalkSink& s) {
    s.on("List");
    for (const auto& x : n.elts) walk(x, s);
}
inline void walk(const ListComp& n, WalkSink& s) {
    s.on("ListComp");
    if (n.elt) walk(*n.elt, s);
    for (const auto& x : n.generators) walk(x, s);
}
inline void walk(const Match& n, WalkSink& s) {
    s.on("Match");
    if (n.subject) walk(*n.subject, s);
    for (const auto& x : n.cases) walk(x, s);
}
inline void walk(const MatchAs& n, WalkSink& s) {
    s.on("MatchAs");
    if (n.pattern && *n.pattern) walk(**n.pattern, s);
}
inline void walk(const MatchClass& n, WalkSink& s) {
    s.on("MatchClass");
    if (n.cls) walk(*n.cls, s);
    for (const auto& x : n.patterns) walk(x, s);
    for (const auto& x : n.kwd_patterns) walk(x, s);
}
inline void walk(const MatchMapping& n, WalkSink& s) {
    s.on("MatchMapping");
    for (const auto& x : n.keys) walk(x, s);
    for (const auto& x : n.patterns) walk(x, s);
}
inline void walk(const MatchOr& n, WalkSink& s) {
    s.on("MatchOr");
    for (const auto& x : n.patterns) walk(x, s);
}
inline void walk(const MatchSequence& n, WalkSink& s) {
    s.on("MatchSequence");
    for (const auto& x : n.patterns) walk(x, s);
}
inline void walk(const MatchSingleton& n, WalkSink& s) {
    s.on("MatchSingleton");
}
inline void walk(const MatchStar& n, WalkSink& s) {
    s.on("MatchStar");
}
inline void walk(const MatchValue& n, WalkSink& s) {
    s.on("MatchValue");
    if (n.value) walk(*n.value, s);
}
inline void walk(const Module& n, WalkSink& s) {
    s.on("Module");
    for (const auto& x : n.body) walk(x, s);
    for (const auto& x : n.type_ignores) walk(x, s);
}
inline void walk(const Name& n, WalkSink& s) {
    s.on("Name");
}
inline void walk(const NamedExpr& n, WalkSink& s) {
    s.on("NamedExpr");
    if (n.target) walk(*n.target, s);
    if (n.value) walk(*n.value, s);
}
inline void walk(const Nonlocal& n, WalkSink& s) {
    s.on("Nonlocal");
}
inline void walk(const ParamSpec& n, WalkSink& s) {
    s.on("ParamSpec");
    if (n.default_value && *n.default_value) walk(**n.default_value, s);
}
inline void walk(const Pass& n, WalkSink& s) {
    s.on("Pass");
}
inline void walk(const Raise& n, WalkSink& s) {
    s.on("Raise");
    if (n.exc && *n.exc) walk(**n.exc, s);
    if (n.cause && *n.cause) walk(**n.cause, s);
}
inline void walk(const Return& n, WalkSink& s) {
    s.on("Return");
    if (n.value && *n.value) walk(**n.value, s);
}
inline void walk(const Set& n, WalkSink& s) {
    s.on("Set");
    for (const auto& x : n.elts) walk(x, s);
}
inline void walk(const SetComp& n, WalkSink& s) {
    s.on("SetComp");
    if (n.elt) walk(*n.elt, s);
    for (const auto& x : n.generators) walk(x, s);
}
inline void walk(const Slice& n, WalkSink& s) {
    s.on("Slice");
    if (n.lower && *n.lower) walk(**n.lower, s);
    if (n.upper && *n.upper) walk(**n.upper, s);
    if (n.step && *n.step) walk(**n.step, s);
}
inline void walk(const Starred& n, WalkSink& s) {
    s.on("Starred");
    if (n.value) walk(*n.value, s);
}
inline void walk(const Subscript& n, WalkSink& s) {
    s.on("Subscript");
    if (n.value) walk(*n.value, s);
    if (n.slice) walk(*n.slice, s);
}
inline void walk(const Suite& n, WalkSink& s) {
    s.on("Suite");
}
inline void walk(const TemplateStr& n, WalkSink& s) {
    s.on("TemplateStr");
    for (const auto& x : n.values) walk(x, s);
}
inline void walk(const Try& n, WalkSink& s) {
    s.on("Try");
    for (const auto& x : n.body) walk(x, s);
    for (const auto& x : n.handlers) walk(x, s);
    for (const auto& x : n.orelse) walk(x, s);
    for (const auto& x : n.finalbody) walk(x, s);
}
inline void walk(const TryStar& n, WalkSink& s) {
    s.on("TryStar");
    for (const auto& x : n.body) walk(x, s);
    for (const auto& x : n.handlers) walk(x, s);
    for (const auto& x : n.orelse) walk(x, s);
    for (const auto& x : n.finalbody) walk(x, s);
}
inline void walk(const Tuple& n, WalkSink& s) {
    s.on("Tuple");
    for (const auto& x : n.elts) walk(x, s);
}
inline void walk(const TypeAlias& n, WalkSink& s) {
    s.on("TypeAlias");
    if (n.name) walk(*n.name, s);
    for (const auto& x : n.type_params) walk(x, s);
    if (n.value) walk(*n.value, s);
}
inline void walk(const TypeIgnore& n, WalkSink& s) {
    s.on("TypeIgnore");
}
inline void walk(const TypeVar& n, WalkSink& s) {
    s.on("TypeVar");
    if (n.bound && *n.bound) walk(**n.bound, s);
    if (n.default_value && *n.default_value) walk(**n.default_value, s);
}
inline void walk(const TypeVarTuple& n, WalkSink& s) {
    s.on("TypeVarTuple");
    if (n.default_value && *n.default_value) walk(**n.default_value, s);
}
inline void walk(const UnaryOp& n, WalkSink& s) {
    s.on("UnaryOp");
    if (n.operand) walk(*n.operand, s);
}
inline void walk(const While& n, WalkSink& s) {
    s.on("While");
    if (n.test) walk(*n.test, s);
    for (const auto& x : n.body) walk(x, s);
    for (const auto& x : n.orelse) walk(x, s);
}
inline void walk(const With& n, WalkSink& s) {
    s.on("With");
    for (const auto& x : n.items) walk(x, s);
    for (const auto& x : n.body) walk(x, s);
}
inline void walk(const Yield& n, WalkSink& s) {
    s.on("Yield");
    if (n.value && *n.value) walk(**n.value, s);
}
inline void walk(const YieldFrom& n, WalkSink& s) {
    s.on("YieldFrom");
    if (n.value) walk(*n.value, s);
}
inline void walk(const alias& n, WalkSink& s) {
    s.on("alias");
}
inline void walk(const arg& n, WalkSink& s) {
    s.on("arg");
    if (n.annotation && *n.annotation) walk(**n.annotation, s);
}
inline void walk(const arguments& n, WalkSink& s) {
    s.on("arguments");
    for (const auto& x : n.posonlyargs) walk(x, s);
    for (const auto& x : n.args) walk(x, s);
    if (n.vararg && *n.vararg) walk(**n.vararg, s);
    for (const auto& x : n.kwonlyargs) walk(x, s);
    for (const auto& x : n.kw_defaults) if (x && *x) walk(**x, s);
    if (n.kwarg && *n.kwarg) walk(**n.kwarg, s);
    for (const auto& x : n.defaults) walk(x, s);
}
inline void walk(const comprehension& n, WalkSink& s) {
    s.on("comprehension");
    if (n.target) walk(*n.target, s);
    if (n.iter) walk(*n.iter, s);
    for (const auto& x : n.ifs) walk(x, s);
}
inline void walk(const keyword& n, WalkSink& s) {
    s.on("keyword");
    if (n.value) walk(*n.value, s);
}
inline void walk(const match_case& n, WalkSink& s) {
    s.on("match_case");
    if (n.pattern) walk(*n.pattern, s);
    if (n.guard && *n.guard) walk(**n.guard, s);
    for (const auto& x : n.body) walk(x, s);
}
inline void walk(const withitem& n, WalkSink& s) {
    s.on("withitem");
    if (n.context_expr) walk(*n.context_expr, s);
    if (n.optional_vars && *n.optional_vars) walk(**n.optional_vars, s);
}

inline void walk(const excepthandler& n, WalkSink& s) {
    std::visit(ov{
        [&](const ExceptHandler& x) { walk(x, s); },
    }, n.v);
}
inline void walk(const expr& n, WalkSink& s) {
    std::visit(ov{
        [&](const Attribute& x) { walk(x, s); },
        [&](const Await& x) { walk(x, s); },
        [&](const BinOp& x) { walk(x, s); },
        [&](const BoolOp& x) { walk(x, s); },
        [&](const Call& x) { walk(x, s); },
        [&](const Compare& x) { walk(x, s); },
        [&](const Constant& x) { walk(x, s); },
        [&](const Dict& x) { walk(x, s); },
        [&](const DictComp& x) { walk(x, s); },
        [&](const FormattedValue& x) { walk(x, s); },
        [&](const GeneratorExp& x) { walk(x, s); },
        [&](const IfExp& x) { walk(x, s); },
        [&](const Interpolation& x) { walk(x, s); },
        [&](const JoinedStr& x) { walk(x, s); },
        [&](const Lambda& x) { walk(x, s); },
        [&](const List& x) { walk(x, s); },
        [&](const ListComp& x) { walk(x, s); },
        [&](const Name& x) { walk(x, s); },
        [&](const NamedExpr& x) { walk(x, s); },
        [&](const Set& x) { walk(x, s); },
        [&](const SetComp& x) { walk(x, s); },
        [&](const Slice& x) { walk(x, s); },
        [&](const Starred& x) { walk(x, s); },
        [&](const Subscript& x) { walk(x, s); },
        [&](const TemplateStr& x) { walk(x, s); },
        [&](const Tuple& x) { walk(x, s); },
        [&](const UnaryOp& x) { walk(x, s); },
        [&](const Yield& x) { walk(x, s); },
        [&](const YieldFrom& x) { walk(x, s); },
    }, n.v);
}
inline void walk(const mod& n, WalkSink& s) {
    std::visit(ov{
        [&](const Expression& x) { walk(x, s); },
        [&](const FunctionType& x) { walk(x, s); },
        [&](const Interactive& x) { walk(x, s); },
        [&](const Module& x) { walk(x, s); },
        [&](const Suite& x) { walk(x, s); },
    }, n.v);
}
inline void walk(const pattern& n, WalkSink& s) {
    std::visit(ov{
        [&](const MatchAs& x) { walk(x, s); },
        [&](const MatchClass& x) { walk(x, s); },
        [&](const MatchMapping& x) { walk(x, s); },
        [&](const MatchOr& x) { walk(x, s); },
        [&](const MatchSequence& x) { walk(x, s); },
        [&](const MatchSingleton& x) { walk(x, s); },
        [&](const MatchStar& x) { walk(x, s); },
        [&](const MatchValue& x) { walk(x, s); },
    }, n.v);
}
inline void walk(const stmt& n, WalkSink& s) {
    std::visit(ov{
        [&](const AnnAssign& x) { walk(x, s); },
        [&](const Assert& x) { walk(x, s); },
        [&](const Assign& x) { walk(x, s); },
        [&](const AsyncFor& x) { walk(x, s); },
        [&](const AsyncFunctionDef& x) { walk(x, s); },
        [&](const AsyncWith& x) { walk(x, s); },
        [&](const AugAssign& x) { walk(x, s); },
        [&](const Break& x) { walk(x, s); },
        [&](const ClassDef& x) { walk(x, s); },
        [&](const Continue& x) { walk(x, s); },
        [&](const Delete& x) { walk(x, s); },
        [&](const Expr& x) { walk(x, s); },
        [&](const For& x) { walk(x, s); },
        [&](const FunctionDef& x) { walk(x, s); },
        [&](const Global& x) { walk(x, s); },
        [&](const If& x) { walk(x, s); },
        [&](const Import& x) { walk(x, s); },
        [&](const ImportFrom& x) { walk(x, s); },
        [&](const Match& x) { walk(x, s); },
        [&](const Nonlocal& x) { walk(x, s); },
        [&](const Pass& x) { walk(x, s); },
        [&](const Raise& x) { walk(x, s); },
        [&](const Return& x) { walk(x, s); },
        [&](const Try& x) { walk(x, s); },
        [&](const TryStar& x) { walk(x, s); },
        [&](const TypeAlias& x) { walk(x, s); },
        [&](const While& x) { walk(x, s); },
        [&](const With& x) { walk(x, s); },
    }, n.v);
}
inline void walk(const type_ignore& n, WalkSink& s) {
    std::visit(ov{
        [&](const TypeIgnore& x) { walk(x, s); },
    }, n.v);
}
inline void walk(const type_param& n, WalkSink& s) {
    std::visit(ov{
        [&](const ParamSpec& x) { walk(x, s); },
        [&](const TypeVar& x) { walk(x, s); },
        [&](const TypeVarTuple& x) { walk(x, s); },
    }, n.v);
}

}  // namespace pyc::ast
