#pragma once
// GENERATED by compiler/tools/gen_ast.py -- DO NOT EDIT.
// Source: CPython 3.14.7
//
// Depth is bounded and reported as a diagnostic (INTERFACES.md §1.2):
// a stack overflow is an uncontrollable crash and cannot be reported,
// which would violate I1 at the very first layer.
#include "pyc/ast/generated.hpp"
#include "pyc/ast/from_json_support.hpp"

namespace pyc::ast {

// forward declarations (the grammar is mutually recursive)
bool from_json(Add& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(And& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(AnnAssign& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Assert& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Assign& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(AsyncFor& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(AsyncFunctionDef& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(AsyncWith& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Attribute& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(AugAssign& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(AugLoad& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(AugStore& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Await& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(BinOp& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(BitAnd& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(BitOr& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(BitXor& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(BoolOp& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Break& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Call& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(ClassDef& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Compare& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Constant& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Continue& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Del& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Delete& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Dict& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(DictComp& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Div& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Eq& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(ExceptHandler& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Expr& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Expression& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(FloorDiv& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(For& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(FormattedValue& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(FunctionDef& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(FunctionType& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(GeneratorExp& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Global& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Gt& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(GtE& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(If& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(IfExp& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Import& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(ImportFrom& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(In& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Interactive& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Interpolation& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Invert& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Is& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(IsNot& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(JoinedStr& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(LShift& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Lambda& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(List& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(ListComp& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Load& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Lt& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(LtE& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(MatMult& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Match& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(MatchAs& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(MatchClass& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(MatchMapping& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(MatchOr& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(MatchSequence& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(MatchSingleton& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(MatchStar& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(MatchValue& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Mod& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Module& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Mult& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Name& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(NamedExpr& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Nonlocal& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Not& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(NotEq& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(NotIn& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Or& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Param& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(ParamSpec& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Pass& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Pow& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(RShift& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Raise& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Return& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Set& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(SetComp& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Slice& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Starred& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Store& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Sub& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Subscript& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Suite& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(TemplateStr& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Try& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(TryStar& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Tuple& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(TypeAlias& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(TypeIgnore& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(TypeVar& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(TypeVarTuple& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(UAdd& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(USub& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(UnaryOp& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(While& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(With& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(Yield& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(YieldFrom& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(alias& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(arg& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(arguments& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(comprehension& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(excepthandler& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(expr& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(keyword& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(match_case& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(mod& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(pattern& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(stmt& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(type_ignore& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(type_param& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(withitem& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(boolop& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(cmpop& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(expr_context& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(operator_& out, const JsonCtx& c, const json::Value& v, Depth d);
bool from_json(unaryop& out, const JsonCtx& c, const json::Value& v, Depth d);

inline bool from_json(boolop& out, const JsonCtx& c, const json::Value& v, Depth d) {
    (void)d;
    std::string_view k; if (!kind_of(c, v, k)) return false;
    if (k == "And") { out.v = And{}; return true; }
    if (k == "Or") { out.v = Or{}; return true; }
    return c.unknown_kind(k, "boolop");
}
inline bool from_json(cmpop& out, const JsonCtx& c, const json::Value& v, Depth d) {
    (void)d;
    std::string_view k; if (!kind_of(c, v, k)) return false;
    if (k == "Eq") { out.v = Eq{}; return true; }
    if (k == "Gt") { out.v = Gt{}; return true; }
    if (k == "GtE") { out.v = GtE{}; return true; }
    if (k == "In") { out.v = In{}; return true; }
    if (k == "Is") { out.v = Is{}; return true; }
    if (k == "IsNot") { out.v = IsNot{}; return true; }
    if (k == "Lt") { out.v = Lt{}; return true; }
    if (k == "LtE") { out.v = LtE{}; return true; }
    if (k == "NotEq") { out.v = NotEq{}; return true; }
    if (k == "NotIn") { out.v = NotIn{}; return true; }
    return c.unknown_kind(k, "cmpop");
}
inline bool from_json(expr_context& out, const JsonCtx& c, const json::Value& v, Depth d) {
    (void)d;
    std::string_view k; if (!kind_of(c, v, k)) return false;
    if (k == "AugLoad") { out.v = AugLoad{}; return true; }
    if (k == "AugStore") { out.v = AugStore{}; return true; }
    if (k == "Del") { out.v = Del{}; return true; }
    if (k == "Load") { out.v = Load{}; return true; }
    if (k == "Param") { out.v = Param{}; return true; }
    if (k == "Store") { out.v = Store{}; return true; }
    return c.unknown_kind(k, "expr_context");
}
inline bool from_json(operator_& out, const JsonCtx& c, const json::Value& v, Depth d) {
    (void)d;
    std::string_view k; if (!kind_of(c, v, k)) return false;
    if (k == "Add") { out.v = Add{}; return true; }
    if (k == "BitAnd") { out.v = BitAnd{}; return true; }
    if (k == "BitOr") { out.v = BitOr{}; return true; }
    if (k == "BitXor") { out.v = BitXor{}; return true; }
    if (k == "Div") { out.v = Div{}; return true; }
    if (k == "FloorDiv") { out.v = FloorDiv{}; return true; }
    if (k == "LShift") { out.v = LShift{}; return true; }
    if (k == "MatMult") { out.v = MatMult{}; return true; }
    if (k == "Mod") { out.v = Mod{}; return true; }
    if (k == "Mult") { out.v = Mult{}; return true; }
    if (k == "Pow") { out.v = Pow{}; return true; }
    if (k == "RShift") { out.v = RShift{}; return true; }
    if (k == "Sub") { out.v = Sub{}; return true; }
    return c.unknown_kind(k, "operator");
}
inline bool from_json(unaryop& out, const JsonCtx& c, const json::Value& v, Depth d) {
    (void)d;
    std::string_view k; if (!kind_of(c, v, k)) return false;
    if (k == "Invert") { out.v = Invert{}; return true; }
    if (k == "Not") { out.v = Not{}; return true; }
    if (k == "UAdd") { out.v = UAdd{}; return true; }
    if (k == "USub") { out.v = USub{}; return true; }
    return c.unknown_kind(k, "unaryop");
}

inline bool from_json(AnnAssign& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.target, c, c.doc.find(v, "target"), d.next())) return false;
    if (!node_one(out.annotation, c, c.doc.find(v, "annotation"), d.next())) return false;
    if (!node_opt(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    if (!i64_one(out.simple, c, c.doc.find(v, "simple"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Assert& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.test, c, c.doc.find(v, "test"), d.next())) return false;
    if (!node_opt(out.msg, c, c.doc.find(v, "msg"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Assign& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.targets, c, c.doc.find(v, "targets"), d.next())) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    if (!str_opt(out.type_comment, c, c.doc.find(v, "type_comment"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(AsyncFor& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.target, c, c.doc.find(v, "target"), d.next())) return false;
    if (!node_one(out.iter, c, c.doc.find(v, "iter"), d.next())) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    if (!node_seq(out.orelse, c, c.doc.find(v, "orelse"), d.next())) return false;
    if (!str_opt(out.type_comment, c, c.doc.find(v, "type_comment"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(AsyncFunctionDef& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_one(out.name, c, c.doc.find(v, "name"))) return false;
    if (!node_one(out.args, c, c.doc.find(v, "args"), d.next())) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    if (!node_seq(out.decorator_list, c, c.doc.find(v, "decorator_list"), d.next())) return false;
    if (!node_opt(out.returns, c, c.doc.find(v, "returns"), d.next())) return false;
    if (!str_opt(out.type_comment, c, c.doc.find(v, "type_comment"))) return false;
    if (!node_seq(out.type_params, c, c.doc.find(v, "type_params"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(AsyncWith& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.items, c, c.doc.find(v, "items"), d.next())) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    if (!str_opt(out.type_comment, c, c.doc.find(v, "type_comment"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Attribute& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    if (!str_one(out.attr, c, c.doc.find(v, "attr"))) return false;
    if (!node_one(out.ctx, c, c.doc.find(v, "ctx"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(AugAssign& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.target, c, c.doc.find(v, "target"), d.next())) return false;
    if (!node_one(out.op, c, c.doc.find(v, "op"), d.next())) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Await& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(BinOp& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.left, c, c.doc.find(v, "left"), d.next())) return false;
    if (!node_one(out.op, c, c.doc.find(v, "op"), d.next())) return false;
    if (!node_one(out.right, c, c.doc.find(v, "right"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(BoolOp& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.op, c, c.doc.find(v, "op"), d.next())) return false;
    if (!node_seq(out.values, c, c.doc.find(v, "values"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Break& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Call& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.func, c, c.doc.find(v, "func"), d.next())) return false;
    if (!node_seq(out.args, c, c.doc.find(v, "args"), d.next())) return false;
    if (!node_seq(out.keywords, c, c.doc.find(v, "keywords"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(ClassDef& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_one(out.name, c, c.doc.find(v, "name"))) return false;
    if (!node_seq(out.bases, c, c.doc.find(v, "bases"), d.next())) return false;
    if (!node_seq(out.keywords, c, c.doc.find(v, "keywords"), d.next())) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    if (!node_seq(out.decorator_list, c, c.doc.find(v, "decorator_list"), d.next())) return false;
    if (!node_seq(out.type_params, c, c.doc.find(v, "type_params"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Compare& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.left, c, c.doc.find(v, "left"), d.next())) return false;
    if (!node_seq(out.ops, c, c.doc.find(v, "ops"), d.next())) return false;
    if (!node_seq(out.comparators, c, c.doc.find(v, "comparators"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Constant& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!const_from_json(out.value, c, c.doc.find(v, "value"))) return false;
    if (!str_opt(out.kind, c, c.doc.find(v, "kind"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Continue& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Delete& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.targets, c, c.doc.find(v, "targets"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Dict& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq_opt(out.keys, c, c.doc.find(v, "keys"), d.next())) return false;
    if (!node_seq(out.values, c, c.doc.find(v, "values"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(DictComp& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.key, c, c.doc.find(v, "key"), d.next())) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    if (!node_seq(out.generators, c, c.doc.find(v, "generators"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(ExceptHandler& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_opt(out.type, c, c.doc.find(v, "type"), d.next())) return false;
    if (!str_opt(out.name, c, c.doc.find(v, "name"))) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Expr& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Expression& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    return true;
}
inline bool from_json(For& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.target, c, c.doc.find(v, "target"), d.next())) return false;
    if (!node_one(out.iter, c, c.doc.find(v, "iter"), d.next())) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    if (!node_seq(out.orelse, c, c.doc.find(v, "orelse"), d.next())) return false;
    if (!str_opt(out.type_comment, c, c.doc.find(v, "type_comment"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(FormattedValue& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    if (!i64_one(out.conversion, c, c.doc.find(v, "conversion"))) return false;
    if (!node_opt(out.format_spec, c, c.doc.find(v, "format_spec"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(FunctionDef& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_one(out.name, c, c.doc.find(v, "name"))) return false;
    if (!node_one(out.args, c, c.doc.find(v, "args"), d.next())) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    if (!node_seq(out.decorator_list, c, c.doc.find(v, "decorator_list"), d.next())) return false;
    if (!node_opt(out.returns, c, c.doc.find(v, "returns"), d.next())) return false;
    if (!str_opt(out.type_comment, c, c.doc.find(v, "type_comment"))) return false;
    if (!node_seq(out.type_params, c, c.doc.find(v, "type_params"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(FunctionType& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.argtypes, c, c.doc.find(v, "argtypes"), d.next())) return false;
    if (!node_one(out.returns, c, c.doc.find(v, "returns"), d.next())) return false;
    return true;
}
inline bool from_json(GeneratorExp& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.elt, c, c.doc.find(v, "elt"), d.next())) return false;
    if (!node_seq(out.generators, c, c.doc.find(v, "generators"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Global& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_seq(out.names, c, c.doc.find(v, "names"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(If& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.test, c, c.doc.find(v, "test"), d.next())) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    if (!node_seq(out.orelse, c, c.doc.find(v, "orelse"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(IfExp& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.test, c, c.doc.find(v, "test"), d.next())) return false;
    if (!node_one(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    if (!node_one(out.orelse, c, c.doc.find(v, "orelse"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Import& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.names, c, c.doc.find(v, "names"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(ImportFrom& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_opt(out.module, c, c.doc.find(v, "module"))) return false;
    if (!node_seq(out.names, c, c.doc.find(v, "names"), d.next())) return false;
    if (!i64_opt(out.level, c, c.doc.find(v, "level"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Interactive& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    return true;
}
inline bool from_json(Interpolation& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    if (!const_from_json(out.str, c, c.doc.find(v, "str"))) return false;
    if (!i64_one(out.conversion, c, c.doc.find(v, "conversion"))) return false;
    if (!node_opt(out.format_spec, c, c.doc.find(v, "format_spec"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(JoinedStr& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.values, c, c.doc.find(v, "values"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Lambda& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.args, c, c.doc.find(v, "args"), d.next())) return false;
    if (!node_one(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(List& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.elts, c, c.doc.find(v, "elts"), d.next())) return false;
    if (!node_one(out.ctx, c, c.doc.find(v, "ctx"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(ListComp& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.elt, c, c.doc.find(v, "elt"), d.next())) return false;
    if (!node_seq(out.generators, c, c.doc.find(v, "generators"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Match& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.subject, c, c.doc.find(v, "subject"), d.next())) return false;
    if (!node_seq(out.cases, c, c.doc.find(v, "cases"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(MatchAs& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_opt(out.pattern, c, c.doc.find(v, "pattern"), d.next())) return false;
    if (!str_opt(out.name, c, c.doc.find(v, "name"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(MatchClass& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.cls, c, c.doc.find(v, "cls"), d.next())) return false;
    if (!node_seq(out.patterns, c, c.doc.find(v, "patterns"), d.next())) return false;
    if (!str_seq(out.kwd_attrs, c, c.doc.find(v, "kwd_attrs"))) return false;
    if (!node_seq(out.kwd_patterns, c, c.doc.find(v, "kwd_patterns"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(MatchMapping& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.keys, c, c.doc.find(v, "keys"), d.next())) return false;
    if (!node_seq(out.patterns, c, c.doc.find(v, "patterns"), d.next())) return false;
    if (!str_opt(out.rest, c, c.doc.find(v, "rest"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(MatchOr& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.patterns, c, c.doc.find(v, "patterns"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(MatchSequence& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.patterns, c, c.doc.find(v, "patterns"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(MatchSingleton& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!const_from_json(out.value, c, c.doc.find(v, "value"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(MatchStar& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_opt(out.name, c, c.doc.find(v, "name"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(MatchValue& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Module& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    if (!node_seq(out.type_ignores, c, c.doc.find(v, "type_ignores"), d.next())) return false;
    return true;
}
inline bool from_json(Name& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_one(out.id, c, c.doc.find(v, "id"))) return false;
    if (!node_one(out.ctx, c, c.doc.find(v, "ctx"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(NamedExpr& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.target, c, c.doc.find(v, "target"), d.next())) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Nonlocal& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_seq(out.names, c, c.doc.find(v, "names"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(ParamSpec& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_one(out.name, c, c.doc.find(v, "name"))) return false;
    if (!node_opt(out.default_value, c, c.doc.find(v, "default_value"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Pass& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Raise& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_opt(out.exc, c, c.doc.find(v, "exc"), d.next())) return false;
    if (!node_opt(out.cause, c, c.doc.find(v, "cause"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Return& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_opt(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Set& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.elts, c, c.doc.find(v, "elts"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(SetComp& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.elt, c, c.doc.find(v, "elt"), d.next())) return false;
    if (!node_seq(out.generators, c, c.doc.find(v, "generators"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Slice& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_opt(out.lower, c, c.doc.find(v, "lower"), d.next())) return false;
    if (!node_opt(out.upper, c, c.doc.find(v, "upper"), d.next())) return false;
    if (!node_opt(out.step, c, c.doc.find(v, "step"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Starred& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    if (!node_one(out.ctx, c, c.doc.find(v, "ctx"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Subscript& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    if (!node_one(out.slice, c, c.doc.find(v, "slice"), d.next())) return false;
    if (!node_one(out.ctx, c, c.doc.find(v, "ctx"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Suite& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    return true;
}
inline bool from_json(TemplateStr& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.values, c, c.doc.find(v, "values"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Try& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    if (!node_seq(out.handlers, c, c.doc.find(v, "handlers"), d.next())) return false;
    if (!node_seq(out.orelse, c, c.doc.find(v, "orelse"), d.next())) return false;
    if (!node_seq(out.finalbody, c, c.doc.find(v, "finalbody"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(TryStar& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    if (!node_seq(out.handlers, c, c.doc.find(v, "handlers"), d.next())) return false;
    if (!node_seq(out.orelse, c, c.doc.find(v, "orelse"), d.next())) return false;
    if (!node_seq(out.finalbody, c, c.doc.find(v, "finalbody"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Tuple& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.elts, c, c.doc.find(v, "elts"), d.next())) return false;
    if (!node_one(out.ctx, c, c.doc.find(v, "ctx"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(TypeAlias& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.name, c, c.doc.find(v, "name"), d.next())) return false;
    if (!node_seq(out.type_params, c, c.doc.find(v, "type_params"), d.next())) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(TypeIgnore& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!i64_one(out.lineno, c, c.doc.find(v, "lineno"))) return false;
    if (!str_one(out.tag, c, c.doc.find(v, "tag"))) return false;
    return true;
}
inline bool from_json(TypeVar& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_one(out.name, c, c.doc.find(v, "name"))) return false;
    if (!node_opt(out.bound, c, c.doc.find(v, "bound"), d.next())) return false;
    if (!node_opt(out.default_value, c, c.doc.find(v, "default_value"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(TypeVarTuple& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_one(out.name, c, c.doc.find(v, "name"))) return false;
    if (!node_opt(out.default_value, c, c.doc.find(v, "default_value"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(UnaryOp& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.op, c, c.doc.find(v, "op"), d.next())) return false;
    if (!node_one(out.operand, c, c.doc.find(v, "operand"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(While& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.test, c, c.doc.find(v, "test"), d.next())) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    if (!node_seq(out.orelse, c, c.doc.find(v, "orelse"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(With& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.items, c, c.doc.find(v, "items"), d.next())) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    if (!str_opt(out.type_comment, c, c.doc.find(v, "type_comment"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(Yield& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_opt(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(YieldFrom& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(alias& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_one(out.name, c, c.doc.find(v, "name"))) return false;
    if (!str_opt(out.asname, c, c.doc.find(v, "asname"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(arg& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_one(out.arg, c, c.doc.find(v, "arg"))) return false;
    if (!node_opt(out.annotation, c, c.doc.find(v, "annotation"), d.next())) return false;
    if (!str_opt(out.type_comment, c, c.doc.find(v, "type_comment"))) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(arguments& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_seq(out.posonlyargs, c, c.doc.find(v, "posonlyargs"), d.next())) return false;
    if (!node_seq(out.args, c, c.doc.find(v, "args"), d.next())) return false;
    if (!node_opt(out.vararg, c, c.doc.find(v, "vararg"), d.next())) return false;
    if (!node_seq(out.kwonlyargs, c, c.doc.find(v, "kwonlyargs"), d.next())) return false;
    if (!node_seq_opt(out.kw_defaults, c, c.doc.find(v, "kw_defaults"), d.next())) return false;
    if (!node_opt(out.kwarg, c, c.doc.find(v, "kwarg"), d.next())) return false;
    if (!node_seq(out.defaults, c, c.doc.find(v, "defaults"), d.next())) return false;
    return true;
}
inline bool from_json(comprehension& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.target, c, c.doc.find(v, "target"), d.next())) return false;
    if (!node_one(out.iter, c, c.doc.find(v, "iter"), d.next())) return false;
    if (!node_seq(out.ifs, c, c.doc.find(v, "ifs"), d.next())) return false;
    if (!i64_one(out.is_async, c, c.doc.find(v, "is_async"))) return false;
    return true;
}
inline bool from_json(keyword& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!str_opt(out.arg, c, c.doc.find(v, "arg"))) return false;
    if (!node_one(out.value, c, c.doc.find(v, "value"), d.next())) return false;
    loc_from_json(out.loc, c, v);
    return true;
}
inline bool from_json(match_case& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.pattern, c, c.doc.find(v, "pattern"), d.next())) return false;
    if (!node_opt(out.guard, c, c.doc.find(v, "guard"), d.next())) return false;
    if (!node_seq(out.body, c, c.doc.find(v, "body"), d.next())) return false;
    return true;
}
inline bool from_json(withitem& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    if (!node_one(out.context_expr, c, c.doc.find(v, "context_expr"), d.next())) return false;
    if (!node_opt(out.optional_vars, c, c.doc.find(v, "optional_vars"), d.next())) return false;
    return true;
}

inline bool from_json(excepthandler& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    std::string_view k; if (!kind_of(c, v, k)) return false;
    if (k == "ExceptHandler") { ExceptHandler n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    return c.unknown_kind(k, "excepthandler");
}
inline bool from_json(expr& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    std::string_view k; if (!kind_of(c, v, k)) return false;
    if (k == "Attribute") { Attribute n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Await") { Await n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "BinOp") { BinOp n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "BoolOp") { BoolOp n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Call") { Call n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Compare") { Compare n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Constant") { Constant n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Dict") { Dict n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "DictComp") { DictComp n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "FormattedValue") { FormattedValue n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "GeneratorExp") { GeneratorExp n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "IfExp") { IfExp n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Interpolation") { Interpolation n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "JoinedStr") { JoinedStr n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Lambda") { Lambda n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "List") { List n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "ListComp") { ListComp n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Name") { Name n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "NamedExpr") { NamedExpr n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Set") { Set n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "SetComp") { SetComp n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Slice") { Slice n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Starred") { Starred n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Subscript") { Subscript n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "TemplateStr") { TemplateStr n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Tuple") { Tuple n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "UnaryOp") { UnaryOp n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Yield") { Yield n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "YieldFrom") { YieldFrom n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    return c.unknown_kind(k, "expr");
}
inline bool from_json(mod& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    std::string_view k; if (!kind_of(c, v, k)) return false;
    if (k == "Expression") { Expression n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "FunctionType") { FunctionType n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Interactive") { Interactive n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Module") { Module n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Suite") { Suite n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    return c.unknown_kind(k, "mod");
}
inline bool from_json(pattern& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    std::string_view k; if (!kind_of(c, v, k)) return false;
    if (k == "MatchAs") { MatchAs n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "MatchClass") { MatchClass n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "MatchMapping") { MatchMapping n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "MatchOr") { MatchOr n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "MatchSequence") { MatchSequence n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "MatchSingleton") { MatchSingleton n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "MatchStar") { MatchStar n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "MatchValue") { MatchValue n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    return c.unknown_kind(k, "pattern");
}
inline bool from_json(stmt& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    std::string_view k; if (!kind_of(c, v, k)) return false;
    if (k == "AnnAssign") { AnnAssign n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Assert") { Assert n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Assign") { Assign n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "AsyncFor") { AsyncFor n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "AsyncFunctionDef") { AsyncFunctionDef n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "AsyncWith") { AsyncWith n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "AugAssign") { AugAssign n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Break") { Break n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "ClassDef") { ClassDef n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Continue") { Continue n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Delete") { Delete n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Expr") { Expr n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "For") { For n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "FunctionDef") { FunctionDef n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Global") { Global n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "If") { If n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Import") { Import n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "ImportFrom") { ImportFrom n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Match") { Match n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Nonlocal") { Nonlocal n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Pass") { Pass n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Raise") { Raise n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Return") { Return n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "Try") { Try n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "TryStar") { TryStar n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "TypeAlias") { TypeAlias n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "While") { While n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "With") { With n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    return c.unknown_kind(k, "stmt");
}
inline bool from_json(type_ignore& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    std::string_view k; if (!kind_of(c, v, k)) return false;
    if (k == "TypeIgnore") { TypeIgnore n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    return c.unknown_kind(k, "type_ignore");
}
inline bool from_json(type_param& out, const JsonCtx& c, const json::Value& v, Depth d) {
    if (!d.ok(c)) return false;
    std::string_view k; if (!kind_of(c, v, k)) return false;
    if (k == "ParamSpec") { ParamSpec n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "TypeVar") { TypeVar n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    if (k == "TypeVarTuple") { TypeVarTuple n; if (!from_json(n, c, v, d)) return false; out.v = std::move(n); return true; }
    return c.unknown_kind(k, "type_param");
}

}  // namespace pyc::ast
