a = {1, 2, 3, 2, 1}
b = {2, 3, 4}
print(sorted(a))
print(len(a))
print(a | b)
print(sorted(a & b))
print(sorted(a - b))
print(sorted(a ^ b))
print(2 in a, 5 in a)
print(a.issubset({1, 2, 3, 4}), a.issuperset({1}))
s = set()
s.add(10)
s.add(20)
s.add(10)
print(sorted(s))
s.discard(20)
print(sorted(s))
print(sorted({x * 2 for x in range(5) if x > 1}))
print(sorted(set([3, 1, 2, 1])))
print(type(a))
print(isinstance(a, set))