// Typed SSA IR -> textual LLVM IR (INTERFACES.md §3 -> §5).
//
// Deliberately a MECHANICAL translation. Every semantic decision was already
// made in lowering and is visible in the IR: ownership, error edges, which
// C-API symbol, which references are stolen. A4's directive says so
// explicitly -- if a program is wrong, that is A2/A3, and papering over it
// here would hide the defect from the layer that owns it.
//
// Text rather than the LLVM C++ API for now: it keeps pyc free of libLLVM
// linkage, and the output is readable, which matters while the backend is new.
#include "pyc/ir/ir.hpp"

#include <map>
#include <set>
#include <cctype>
#include <sstream>

namespace pyc {
using ir::Ownership;

namespace {

std::string escape(const std::string& s) {
    static const char* hex = "0123456789ABCDEF";
    std::string o;
    for (unsigned char c : s) {
        if (c == '"' || c == '\\' || c < 0x20 || c >= 0x7F) {
            o += '\\'; o += hex[c >> 4]; o += hex[c & 15];
        } else o += (char)c;
    }
    return o;
}

class Codegen {
public:
    explicit Codegen(const ir::Module& m) : m_(m) {}

    std::string run() {
        o_ << "; generated by pyc from " << m_.source_file << "\n";
        o_ << "target triple = \"x86_64-unknown-linux-gnu\"\n\n";
        for (std::size_t i = 0; i < m_.functions.size(); ++i) emit_function(i);
        emit_constants();
        emit_declarations();
        return o_.str();
    }

private:
    const ir::Module& m_;
    std::ostringstream o_;
    std::map<std::string, std::string> strs_;   // text -> global name
    std::set<std::string> decls_;
    int tmp_ = 0;
    // An IR block does not map to one LLVM block: every may-raise call emits a
    // null check, which ends the current LLVM block and starts a `cont` label.
    // A phi's predecessor is therefore the LAST label an IR block emitted, not
    // "bb<index>". LLVM's verifier caught this as "PHI node entries do not
    // match predecessors" -- exactly the check that exists to catch it.
    std::map<std::size_t, std::string> tail_label_;
    std::size_t cur_block_ = 0;

    std::string cstr(const std::string& text) {
        auto it = strs_.find(text);
        if (it != strs_.end()) return it->second;
        std::string name = "@.str" + std::to_string(strs_.size());
        strs_[text] = name;
        return name;
    }
    std::string fresh() { return "%t" + std::to_string(tmp_++); }
    void need(const std::string& decl) { decls_.insert(decl); }

    // Unique per function, because Python names are not: two classes may each
    // define `who`, and a name-based symbol collides in LLVM.
    std::string fname(std::size_t idx) const {
        const ir::Function& f = m_.functions[idx];
        if (f.name == "__main__") return "@__pyc_main";
        std::string safe;
        for (char c : f.name)
            safe += (std::isalnum((unsigned char)c) || c == '_') ? c : '_';
        return "@pyf" + std::to_string(idx) + "_" + safe;
    }
    // Value id 0 is the null value: it prints as an LLVM null pointer, which
    // is how a nullable C-API argument such as PySet_New(NULL) is passed.
    static std::string v(const ir::Value& x) {
        return x.id ? ("%v" + std::to_string(x.id)) : std::string("null");
    }

    void emit_function(std::size_t idx) {
        const ir::Function& f = m_.functions[idx];
        bool is_main = (f.name == "__main__");
        // The module body returns i32 (0/-1); a Python function returns a new
        // reference or null. Both are the C-API convention from INTERFACES §3.
        o_ << (is_main ? "define i32 " : "define ptr ") << fname(idx)
           << "(ptr %locals) {\n";
        for (std::size_t b = 0; b < f.blocks.size(); ++b) {
            o_ << "bb" << b << ":\n";
            cur_block_ = b;
            tail_label_[b] = "bb" + std::to_string(b);
            emit_block(f, f.blocks[b], b, is_main);
        }
        o_ << "}\n\n";
    }

    void emit_block(const ir::Function& f, const ir::Block& b,
                    std::size_t idx, bool is_main) {
        (void)idx;
        for (const ir::Instr& in : b.instrs) emit_instr(f, in, is_main);
        // A block with no terminator falls through; lowering guarantees one,
        // but an empty landing pad target would otherwise emit invalid IR.
        if (b.instrs.empty() || !ir::is_terminator(b.instrs.back().op))
            o_ << "  unreachable\n";
    }



    // Emit the null-check that turns a may-raise call into an explicit edge.
    void check(const ir::Instr& in, const std::string& val, bool is_ptr) {
        if (!in.on_error) return;
        std::string c = fresh();
        o_ << "  " << c << " = icmp " << (is_ptr ? "eq ptr " : "slt i32 ")
           << val << (is_ptr ? ", null\n" : ", 0\n");
        std::string cont = "cont" + std::to_string(tmp_++);
        o_ << "  br i1 " << c << ", label %bb" << *in.on_error
           << ", label %" << cont << "\n";
        o_ << cont << ":\n";
        tail_label_[cur_block_] = cont;   // this is now the block's exit label
    }

    void emit_instr(const ir::Function& f, const ir::Instr& in, bool is_main) {
        using ir::Op;
        switch (in.op) {
            case Op::ConstInt:
                need("declare ptr @pyc_rt_int_from_text(ptr)");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_int_from_text(ptr "
                   << cstr(in.text) << ")\n";
                check(in, v(*in.result), true);
                break;
            case Op::ConstStr:
                need("declare ptr @pyc_rt_str(ptr, i64)");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_str(ptr "
                   << cstr(in.text) << ", i64 " << in.text.size() << ")\n";
                check(in, v(*in.result), true);
                break;
            case Op::ConstBytes:
                need("declare ptr @pyc_rt_bytes(ptr, i64)");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_bytes(ptr "
                   << cstr(in.text) << ", i64 " << in.text.size() << ")\n";
                check(in, v(*in.result), true);
                break;
            case Op::ConstFloat:
                need("declare ptr @PyFloat_FromDouble(double)");
                o_ << "  " << v(*in.result) << " = call ptr @PyFloat_FromDouble(double "
                   << in.text << ")\n";
                check(in, v(*in.result), true);
                break;
            case Op::ConstBool: {
                need("declare ptr @PyBool_FromLong(i64)");
                o_ << "  " << v(*in.result) << " = call ptr @PyBool_FromLong(i64 "
                   << (in.text == "True" ? 1 : 0) << ")\n";
                check(in, v(*in.result), true);
                break;
            }
            case Op::ConstNone:
                need("declare ptr @pyc_rt_none()");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_none()\n";
                break;
            case Op::LoadGlobal:
                need("declare ptr @pyc_rt_load_global(ptr)");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_load_global(ptr "
                   << cstr(in.text) << ")\n";
                check(in, v(*in.result), true);
                break;
            case Op::StoreGlobal: {
                need("declare i32 @pyc_rt_store_global(ptr, ptr)");
                std::string r = fresh();
                o_ << "  " << r << " = call i32 @pyc_rt_store_global(ptr "
                   << cstr(in.text) << ", ptr " << v(in.args[0]) << ")\n";
                break;
            }
            case Op::LoadLocal:
                need("declare ptr @pyc_rt_load_local(ptr, i32, ptr)");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_load_local(ptr %locals, i32 "
                   << in.target << ", ptr " << cstr(in.text) << ")\n";
                check(in, v(*in.result), true);
                break;
            case Op::StoreLocal:
                need("declare void @pyc_rt_store_local(ptr, i32, ptr)");
                o_ << "  call void @pyc_rt_store_local(ptr %locals, i32 " << in.target
                   << ", ptr " << v(in.args[0]) << ")\n";
                break;
            case Op::IncRef:
                need("declare void @Py_IncRef(ptr)");
                o_ << "  call void @Py_IncRef(ptr " << v(in.args[0]) << ")\n";
                break;
            case Op::DecRef:
                need("declare void @Py_DecRef(ptr)");
                o_ << "  call void @Py_DecRef(ptr " << v(in.args[0]) << ")\n";
                break;
            case Op::CallCApi: emit_capi(in); break;
            case Op::CallObject: emit_call(in); break;
            case Op::IsTrue: {
                need("declare i32 @PyObject_IsTrue(ptr)");
                o_ << "  " << v(*in.result) << " = call i32 @PyObject_IsTrue(ptr "
                   << v(in.args[0]) << ")\n";
                check(in, v(*in.result), false);
                break;
            }
            case Op::Is: {
                std::string c = fresh();
                o_ << "  " << c << " = icmp eq ptr " << v(in.args[0]) << ", "
                   << v(in.args[1]) << "\n";
                o_ << "  " << v(*in.result) << " = zext i1 " << c << " to i32\n";
                break;
            }
            case Op::IntNot: {
                std::string c = fresh();
                o_ << "  " << c << " = icmp eq i32 " << v(in.args[0]) << ", 0\n";
                o_ << "  " << v(*in.result) << " = zext i1 " << c << " to i32\n";
                break;
            }
            case Op::Raise: {
                need("declare i32 @pyc_rt_raise(ptr)");
                std::string r = fresh();
                o_ << "  " << r << " = call i32 @pyc_rt_raise(ptr "
                   << v(in.args[0]) << ")\n";
                // Always fails, so control always leaves by the error edge.
                o_ << "  br label %bb" << (in.on_error ? *in.on_error : 0) << "\n";
                break;
            }
            case Op::BuildClass: {
                need("declare ptr @pyc_rt_build_class(ptr, ptr, ptr)");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_build_class(ptr "
                   << cstr(in.text) << ", ptr " << v(in.args[0])
                   << ", ptr " << v(in.args[1]) << ")\n";
                check(in, v(*in.result), true);
                break;
            }
            case Op::ImportModule: {
                if (in.imm) {
                    // __import__(name, NULL, NULL, NULL, 0) returns the
                    // top-level package, which is what `import a.b` binds.
                    need("declare ptr @PyImport_ImportModuleLevel(ptr, ptr, ptr, ptr, i32)");
                    o_ << "  " << v(*in.result)
                       << " = call ptr @PyImport_ImportModuleLevel(ptr " << cstr(in.text)
                       << ", ptr null, ptr null, ptr null, i32 0)\n";
                } else {
                    // Dotted names yield the named module itself here.
                    need("declare ptr @PyImport_ImportModule(ptr)");
                    o_ << "  " << v(*in.result) << " = call ptr @PyImport_ImportModule(ptr "
                       << cstr(in.text) << ")\n";
                }
                check(in, v(*in.result), true);
                break;
            }
            case Op::IterNext: {
                need("declare ptr @PyIter_Next(ptr)");
                need("declare ptr @PyErr_Occurred()");
                o_ << "  " << v(*in.result) << " = call ptr @PyIter_Next(ptr "
                   << v(in.args[0]) << ")\n";
                std::string isnull = fresh(), maybe = "iterend" + std::to_string(tmp_++);
                o_ << "  " << isnull << " = icmp eq ptr " << v(*in.result) << ", null\n";
                o_ << "  br i1 " << isnull << ", label %" << maybe
                   << ", label %bb" << in.target << "\n";
                o_ << maybe << ":\n";
                // NULL means exhausted OR failed; only PyErr_Occurred tells
                // them apart, and conflating them would swallow an exception
                // raised inside __next__.
                std::string err = fresh(), haserr = fresh();
                o_ << "  " << err << " = call ptr @PyErr_Occurred()\n";
                o_ << "  " << haserr << " = icmp ne ptr " << err << ", null\n";
                o_ << "  br i1 " << haserr << ", label %bb"
                   << (in.on_error ? *in.on_error : in.target_else)
                   << ", label %bb" << in.target_else << "\n";
                break;
            }
            case Op::Phi: {
                o_ << "  " << v(*in.result) << " = phi ptr ";
                for (std::size_t i = 0; i < in.args.size(); ++i) {
                    auto it = tail_label_.find(in.phi_blocks[i]);
                    std::string lbl = (it != tail_label_.end()) ? it->second
                                    : ("bb" + std::to_string(in.phi_blocks[i]));
                    o_ << (i ? ", " : "") << "[ " << v(in.args[i]) << ", %" << lbl << " ]";
                }
                o_ << "\n";
                break;
            }
            case Op::MakeFunction: {
                need("declare ptr @pyc_rt_make_function(ptr, ptr, i32, i32, ptr)");
                std::size_t ti = (std::size_t)in.imm;
                bool valid = in.has_imm && ti < m_.functions.size();
                const ir::Function* t = valid ? &m_.functions[ti] : nullptr;
                // The parameter-name table lets the callee bind keywords.
                std::string names = t ? argnames_global(ti) : "null";
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_make_function(ptr "
                   << cstr(in.text) << ", ptr " << (t ? fname(ti) : "null")
                   << ", i32 " << (t ? t->params.size() : 0)
                   << ", i32 " << (t ? t->locals.size() : 0)
                   << ", ptr " << names << ")\n";
                check(in, v(*in.result), true);
                break;
            }
            case Op::Br:
                o_ << "  br label %bb" << in.target << "\n";
                break;
            case Op::CondBr: {
                std::string c = fresh();
                o_ << "  " << c << " = icmp ne i32 " << v(in.args[0]) << ", 0\n";
                o_ << "  br i1 " << c << ", label %bb" << in.target
                   << ", label %bb" << in.target_else << "\n";
                break;
            }
            case Op::Return:
                if (is_main) o_ << "  ret i32 0\n";
                else if (!in.args.empty()) o_ << "  ret ptr " << v(in.args[0]) << "\n";
                else { need("declare ptr @pyc_rt_none()");
                       std::string n = fresh();
                       o_ << "  " << n << " = call ptr @pyc_rt_none()\n";
                       o_ << "  ret ptr " << n << "\n"; }
                break;
            case Op::ReturnErr:
                o_ << (is_main ? "  ret i32 -1\n" : "  ret ptr null\n");
                break;
        }
        (void)f;
    }

    void emit_capi(const ir::Instr& in) {
        bool ptr_ret = (in.result_ownership == Ownership::Owned
                     || in.result_ownership == Ownership::Borrowed
                     || in.result_ownership == Ownership::AlwaysNull);
        std::ostringstream sig, call;
        sig << "declare " << (ptr_ret ? "ptr" : "i32") << " @" << in.text << "(";
        call << "  " << v(*in.result) << " = call " << (ptr_ret ? "ptr" : "i32")
             << " @" << in.text << "(";
        // The immediate occupies its true C parameter position, which is what
        // makes the steal indices in §4's table line up with reality.
        std::size_t ai = 0;
        std::size_t total = in.args.size() + (in.has_imm ? 1 : 0);
        for (std::size_t p = 0; p < total; ++p) {
            if (p) { sig << ", "; call << ", "; }
            if (in.has_imm && (int)p == imm_pos(in, total)) {
                sig << "i64"; call << "i64 " << in.imm;
            } else {
                sig << "ptr"; call << "ptr " << v(in.args[ai++]);
            }
        }
        sig << ")"; call << ")\n";
        need(sig.str());
        o_ << call.str();
        check(in, v(*in.result), ptr_ret);
    }

    // Lowering does not record imm_pos in the instruction, so recover it:
    // a size argument leads (PyList_New), an index sits at parameter 1
    // (PyList_SetItem), and a compare opid trails (PyObject_RichCompare).
    static int imm_pos(const ir::Instr& in, std::size_t total) {
        if (in.args.empty()) return 0;
        if (in.text == "PyObject_RichCompare") return (int)total - 1;
        return 1;
    }

    void emit_call(const ir::Instr& in) {
        need("declare ptr @pyc_rt_call(ptr, ptr, i64)");
        std::size_t n = in.args.size() - 1;
        std::string arr = fresh();
        o_ << "  " << arr << " = alloca [" << (n ? n : 1) << " x ptr]\n";
        for (std::size_t i = 0; i < n; ++i) {
            std::string p = fresh();
            o_ << "  " << p << " = getelementptr [" << (n ? n : 1)
               << " x ptr], ptr " << arr << ", i64 0, i64 " << i << "\n";
            o_ << "  store ptr " << v(in.args[i + 1]) << ", ptr " << p << "\n";
        }
        o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_call(ptr "
           << v(in.args[0]) << ", ptr " << arr << ", i64 " << n << ")\n";
        check(in, v(*in.result), true);
    }

    std::map<std::string, std::string> argnames_;
    std::string argnames_global(std::size_t idx) {
        const ir::Function& f = m_.functions[idx];
        if (f.params.empty()) return "null";
        auto it = argnames_.find(std::to_string(idx));
        if (it != argnames_.end()) return it->second;
        std::string g = "@.args" + std::to_string(idx);
        std::string body = "[" + std::to_string(f.params.size()) + " x ptr] [";
        for (std::size_t i = 0; i < f.params.size(); ++i)
            body += (i ? ", ptr " : "ptr ") + cstr(f.params[i]);
        body += "]";
        argnames_[std::to_string(idx)] = g;
        argname_defs_.push_back(g + " = private unnamed_addr constant " + body);
        return g;
    }
    std::vector<std::string> argname_defs_;

    void emit_constants() {
        for (const std::string& d : argname_defs_) o_ << d << "\n";
        o_ << "\n";
        for (const auto& [text, name] : strs_)
            o_ << name << " = private unnamed_addr constant ["
               << text.size() + 1 << " x i8] c\"" << escape(text) << "\\00\"\n";
    }
    void emit_declarations() {
        o_ << "\n";
        for (const std::string& d : decls_) o_ << d << "\n";
    }
};

}  // namespace

std::string codegen_llvm(const ir::Module& m) { return Codegen(m).run(); }

}  // namespace pyc
