// Typed SSA IR -> textual LLVM IR (INTERFACES.md §3 -> §5).
//
// Deliberately a MECHANICAL translation. Every semantic decision was already
// made in lowering and is visible in the IR: ownership, error edges, which
// C-API symbol, which references are stolen. A4's directive says so
// explicitly -- if a program is wrong, that is A2/A3, and papering over it
// here would hide the defect from the layer that owns it.
//
// Text rather than the LLVM C++ API for now: it keeps pyc free of libLLVM
// linkage, and the output is readable, which matters while the backend is new.
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include "pyc/ir/ir.hpp"
#include "pyc/rt/capi.hpp"

#include <map>
#include <set>
#include <cctype>
#include <sstream>

namespace pyc {
using ir::Ownership;

namespace {

// Emit the IEEE-754 bits, which LLVM always accepts and which cannot round.
//
// Appending ".0" when the text had no '.' was not enough: "1e-300" contains an
// 'e' and so was passed through unchanged, and LLVM rejects a floating literal
// with an exponent but no decimal point ("integer constant must have integer
// type"). inf and nan have no valid decimal spelling at all. The hex form has
// none of those cases, and is exact by construction rather than by trusting a
// decimal round-trip.
//
// The IR listing keeps the readable decimal -- this is only the LLVM operand.
std::string fp(const std::string& text) {
    double d = std::strtod(text.c_str(), nullptr);
    std::uint64_t bits;
    static_assert(sizeof d == sizeof bits, "double is not 64-bit");
    std::memcpy(&bits, &d, sizeof bits);
    char buf[32];
    std::snprintf(buf, sizeof buf, "0x%016llX",
                  static_cast<unsigned long long>(bits));
    return buf;
}

std::string escape(const std::string& s) {
    static const char* hex = "0123456789ABCDEF";
    std::string o;
    for (unsigned char c : s) {
        if (c == '"' || c == '\\' || c < 0x20 || c >= 0x7F) {
            o += '\\'; o += hex[c >> 4]; o += hex[c & 15];
        } else o += (char)c;
    }
    return o;
}

class Codegen {
public:
    explicit Codegen(const ir::Module& m) : m_(m) {}

    std::string run() {
        o_ << "; generated by pyc from " << m_.source_file << "\n";
        o_ << "target triple = \"x86_64-unknown-linux-gnu\"\n\n";
        for (std::size_t i = 0; i < m_.functions.size(); ++i) emit_function(i);
        emit_pyconsts();
        emit_constants();
        emit_declarations();
        return o_.str();
    }

private:
    const ir::Module& m_;
    std::ostringstream o_;
    std::map<std::string, std::string> strs_;   // text -> global name
    std::set<std::string> decls_;
    int tmp_ = 0;
    // An IR block does not map to one LLVM block: every may-raise call emits a
    // null check, which ends the current LLVM block and starts a `cont` label.
    // A phi's predecessor is therefore the LAST label an IR block emitted, not
    // "bb<index>". LLVM's verifier caught this as "PHI node entries do not
    // match predecessors" -- exactly the check that exists to catch it.
    std::ostringstream pre_;      // instructions that must precede a call
    std::map<std::size_t, std::string> tail_label_;
    std::size_t cur_block_ = 0;

    std::string cstr(const std::string& text) {
        auto it = strs_.find(text);
        if (it != strs_.end()) return it->second;
        std::string name = "@.str" + std::to_string(strs_.size());
        strs_[text] = name;
        return name;
    }

    // A str literal used to be BUILT at every evaluation: `obj.attr` called
    // pyc_rt_str for "attr" each time round the loop. CPython interns its
    // literals into the code object once, so it does none of that -- and the
    // difference was not only speed. Every one of those allocations could
    // fail, and a failed one went straight into the next C-API call as a null:
    // Lib/test/test_pyexpat installs a no-memory hook on purpose and pyc
    // segfaulted there, where CPython raises MemoryError.
    //
    // Each distinct literal now gets one slot in a module-level table, filled
    // once by __pyc_init_consts before the module body runs. A use is a load
    // and an incref, which keeps the Owned contract the rest of the compiler
    // relies on without allocating.
    // Keyed by KIND as well as text: the int 1 and the str "1" are different
    // objects with the same spelling, and a text-only key would hand one of
    // them the other's slot.
    int const_slot(char kind, const std::string& text) {
        std::string key = std::string(1, kind) + '\0' + text;
        auto it = pyconst_.find(key);
        if (it != pyconst_.end()) return it->second;
        int slot = (int)pyconst_.size();
        pyconst_[key] = slot;
        pyconst_order_.push_back({kind, text});
        return slot;
    }
    std::map<std::string, int> pyconst_;
    std::vector<std::pair<char, std::string>> pyconst_order_;

    // A literal use: load the prebuilt object and take a reference. Never
    // fails, so no error edge is emitted even where the IR carries one -- the
    // table was filled at startup or the program never began.
    void emit_const_use(const ir::Instr& in, char kind) {
        need("declare void @Py_IncRef(ptr)");
        int slot = const_slot(kind, in.text);
        std::string p = fresh();
        o_ << "  " << p << " = getelementptr inbounds ptr, ptr "
           << "@.pyconsts, i64 " << slot << "\n";
        o_ << "  " << v(*in.result) << " = load ptr, ptr " << p << "\n";
        o_ << "  call void @Py_IncRef(ptr " << v(*in.result) << ")\n";
    }
    std::string fresh() { return "%t" + std::to_string(tmp_++); }
    void need(const std::string& decl) { decls_.insert(decl); }

    // Unique per function, because Python names are not: two classes may each
    // define `who`, and a name-based symbol collides in LLVM.
    std::string fname(std::size_t idx) const {
        const ir::Function& f = m_.functions[idx];
        if (f.name == "__main__") return "@__pyc_main";
        std::string safe;
        for (char c : f.name)
            safe += (std::isalnum((unsigned char)c) || c == '_') ? c : '_';
        return "@pyf" + std::to_string(idx) + "_" + safe;
    }
    // Value id 0 is the null value: it prints as an LLVM null pointer, which
    // is how a nullable C-API argument such as PySet_New(NULL) is passed.
    static std::string v(const ir::Value& x) {
        return x.id ? ("%v" + std::to_string(x.id)) : std::string("null");
    }

    void emit_function(std::size_t idx) {
        const ir::Function& f = m_.functions[idx];
        bool is_main = (f.name == "__main__");

        // Two passes. A phi's predecessor label is the LAST label its
        // predecessor block emitted, and a block can be a phi predecessor
        // while being emitted LATER -- try/finally converges the normal path,
        // the unwind path and every return on one block, and those edges run
        // in both directions. A single pass resolved forward references to
        // "bb<index>", which LLVM rejected as "PHI node entries do not match
        // predecessors". The first pass discovers the tail labels; the second
        // emits with all of them known. Counters are restored in between so
        // both passes generate identical names.
        int saved_tmp = tmp_;
        std::ostringstream discard;
        allocas_.clear();
        o_.swap(discard);
        emit_blocks(f, idx, is_main);
        o_.swap(discard);
        auto hoisted = allocas_;
        allocas_.clear();
        tmp_ = saved_tmp;

        o_ << (is_main ? "define i32 " : "define ptr ") << fname(idx)
           << "(ptr %locals) {\n";
        if (!hoisted.empty()) {
            o_ << "entry:\n";
            for (const auto& [name, n] : hoisted)
                o_ << "  " << name << " = alloca [" << n << " x ptr]\n";
            o_ << "  br label %bb0\n";
        }
        emit_blocks(f, idx, is_main);
        o_ << "}\n\n";
    }

    void emit_blocks(const ir::Function& f, std::size_t idx, bool is_main) {
        (void)idx;
        for (std::size_t b = 0; b < f.blocks.size(); ++b) {
            o_ << "bb" << b << ":\n";
            cur_block_ = b;
            tail_label_[b] = "bb" + std::to_string(b);
            // The literal table has to be filled before ANY of it is read, and
            // the module body is the first thing that runs. Emitted inside
            // bb0 rather than in a separate entry block so the block numbering
            // the rest of codegen depends on is untouched.
            if (is_main && b == 0) {
                std::string rc = fresh(), bad = fresh();
                o_ << "  " << rc << " = call i32 @__pyc_init_consts()\n";
                o_ << "  " << bad << " = icmp slt i32 " << rc << ", 0\n";
                std::string cont = "cont" + std::to_string(tmp_++);
                o_ << "  br i1 " << bad << ", label %constfail, label %"
                   << cont << "\n";
                o_ << "constfail:\n  ret i32 1\n";
                o_ << cont << ":\n";
                tail_label_[b] = cont;
            }
            emit_block(f, f.blocks[b], b, is_main);
        }
    }

    void emit_block(const ir::Function& f, const ir::Block& b,
                    std::size_t idx, bool is_main) {
        (void)idx;
        for (const ir::Instr& in : b.instrs) emit_instr(f, in, is_main);
        // A block with no terminator falls through; lowering guarantees one,
        // but an empty landing pad target would otherwise emit invalid IR.
        if (b.instrs.empty() || !ir::is_terminator(b.instrs.back().op))
            o_ << "  unreachable\n";
    }



    // Emit the null-check that turns a may-raise call into an explicit edge.
    void check(const ir::Instr& in, const std::string& val, bool is_ptr) {
        if (!in.on_error) return;
        std::string c = fresh();
        o_ << "  " << c << " = icmp " << (is_ptr ? "eq ptr " : "slt i32 ")
           << val << (is_ptr ? ", null\n" : ", 0\n");
        std::string cont = "cont" + std::to_string(tmp_++);
        o_ << "  br i1 " << c << ", label %bb" << *in.on_error
           << ", label %" << cont << "\n";
        o_ << cont << ":\n";
        tail_label_[cur_block_] = cont;   // this is now the block's exit label
    }

    void emit_instr(const ir::Function& f, const ir::Instr& in, bool is_main) {
        using ir::Op;
        switch (in.op) {
            case Op::ConstInt:  emit_const_use(in, 'i'); break;
            case Op::ConstStr:  emit_const_use(in, 's'); break;
            case Op::ConstBytes: emit_const_use(in, 'b'); break;
            case Op::AddTraceback: {
                need("declare void @pyc_rt_add_traceback(ptr, ptr, ptr, i32)");
                // One code object per site, built once and reused: a raise
                // inside a loop must not rebuild it.
                std::string cache = "@.tbcache" + std::to_string(tb_n_++);
                genexp_caches_.push_back(cache + " = internal global ptr null");
                o_ << "  call void @pyc_rt_add_traceback(ptr " << cache
                   << ", ptr " << cstr(m_.source_file)
                   << ", ptr " << cstr(in.text)
                   << ", i32 " << in.loc.line << ")\n";
                break;
            }
            case Op::MakeGenFunc: {
                need("declare ptr @pyc_rt_make_genfunc(ptr, i64, ptr, ptr, ptr)");
                std::string cache = "@.gfcache" + std::to_string(genexp_n_++);
                genexp_caches_.push_back(cache + " = internal global ptr null");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_make_genfunc(ptr "
                   << cstr(in.text) << ", i64 " << in.text.size()
                   << ", ptr " << cache
                   << ", ptr " << v(in.args[0])
                   << ", ptr " << v(in.args[1]) << ")\n";
                check(in, v(*in.result), true);
                break;
            }
            case Op::MakeGenexp: {
                need("declare ptr @pyc_rt_make_genexp(ptr, i64, ptr, ptr, ptr)");
                // One cache slot per call site: the code object is unmarshalled
                // once, not on every evaluation of the expression.
                std::string cache = "@.gxcache" + std::to_string(genexp_n_++);
                genexp_caches_.push_back(cache + " = internal global ptr null");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_make_genexp(ptr "
                   << cstr(in.text) << ", i64 " << in.text.size()
                   << ", ptr " << cache
                   << ", ptr " << v(in.args[0])
                   << ", ptr " << v(in.args[1]) << ")\n";
                check(in, v(*in.result), true);
                break;
            }
            case Op::ConstFloat: emit_const_use(in, 'f'); break;
            case Op::ConstBool: {
                need("declare ptr @PyBool_FromLong(i64)");
                o_ << "  " << v(*in.result) << " = call ptr @PyBool_FromLong(i64 "
                   << (in.text == "True" ? 1 : 0) << ")\n";
                check(in, v(*in.result), true);
                break;
            }
            case Op::ConstNone:
                need("declare ptr @pyc_rt_none()");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_none()\n";
                break;
            case Op::ConstEllipsis:
                need("declare ptr @pyc_rt_ellipsis()");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_ellipsis()\n";
                break;
            case Op::LoadGlobal:
                need("declare ptr @pyc_rt_load_global(ptr)");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_load_global(ptr "
                   << cstr(in.text) << ")\n";
                check(in, v(*in.result), true);
                break;
            case Op::ConstNull:
                // No call: materialise the null pointer into an SSA name so a
                // phi can take it as an operand.
                o_ << "  " << v(*in.result) << " = select i1 true, ptr null, ptr null\n";
                break;
            case Op::LoadClassName:
                need("declare ptr @pyc_rt_load_classname(ptr, ptr)");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_load_classname(ptr "
                   << v(in.args[0]) << ", ptr " << cstr(in.text) << ")\n";
                check(in, v(*in.result), true);
                break;
            case Op::StoreGlobal: {
                need("declare i32 @pyc_rt_store_global(ptr, ptr)");
                std::string r = fresh();
                o_ << "  " << r << " = call i32 @pyc_rt_store_global(ptr "
                   << cstr(in.text) << ", ptr " << v(in.args[0]) << ")\n";
                break;
            }
            case Op::LoadLocal:
                need("declare ptr @pyc_rt_load_local(ptr, i32, ptr)");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_load_local(ptr %locals, i32 "
                   << in.target << ", ptr " << cstr(in.text) << ")\n";
                check(in, v(*in.result), true);
                break;
            case Op::DelLocal: {
                need("declare i32 @pyc_rt_del_local(ptr, i32, ptr)");
                std::string r = fresh();
                o_ << "  " << r << " = call i32 @pyc_rt_del_local(ptr %locals, i32 "
                   << in.target << ", ptr " << cstr(in.text) << ")\n";
                check(in, r, false);   // int: negative is failure
                break;
            }
            case Op::StoreLocal:
                need("declare void @pyc_rt_store_local(ptr, i32, ptr)");
                o_ << "  call void @pyc_rt_store_local(ptr %locals, i32 " << in.target
                   << ", ptr " << v(in.args[0]) << ")\n";
                break;
            case Op::IncRef:
                need("declare void @Py_IncRef(ptr)");
                o_ << "  call void @Py_IncRef(ptr " << v(in.args[0]) << ")\n";
                break;
            case Op::DecRef:
                need("declare void @Py_DecRef(ptr)");
                o_ << "  call void @Py_DecRef(ptr " << v(in.args[0]) << ")\n";
                break;
            case Op::CallCApi: emit_capi(in); break;
            case Op::CallObject: emit_call(in); break;
            case Op::IsTrue: {
                need("declare i32 @PyObject_IsTrue(ptr)");
                o_ << "  " << v(*in.result) << " = call i32 @PyObject_IsTrue(ptr "
                   << v(in.args[0]) << ")\n";
                check(in, v(*in.result), false);
                break;
            }
            case Op::Is: {
                std::string c = fresh();
                o_ << "  " << c << " = icmp eq ptr " << v(in.args[0]) << ", "
                   << v(in.args[1]) << "\n";
                o_ << "  " << v(*in.result) << " = zext i1 " << c << " to i32\n";
                break;
            }
            case Op::IntNot: {
                std::string c = fresh();
                o_ << "  " << c << " = icmp eq i32 " << v(in.args[0]) << ", 0\n";
                o_ << "  " << v(*in.result) << " = zext i1 " << c << " to i32\n";
                break;
            }
            case Op::DelGlobal: {
                need("declare i32 @pyc_rt_del_global(ptr)");
                o_ << "  " << v(*in.result) << " = call i32 @pyc_rt_del_global(ptr "
                   << cstr(in.text) << ")\n";
                check(in, v(*in.result), false);
                break;
            }
            case Op::CellNew: {
                need("declare ptr @PyCell_New(ptr)");
                o_ << "  " << v(*in.result) << " = call ptr @PyCell_New(ptr "
                   << (in.args.empty() ? "null" : v(in.args[0])) << ")\n";
                check(in, v(*in.result), true);
                break;
            }
            case Op::CellGet: {
                need("declare ptr @pyc_rt_cell_get(ptr)");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_cell_get(ptr "
                   << v(in.args[0]) << ")\n";
                check(in, v(*in.result), true);
                break;
            }
            case Op::CellSet: {
                need("declare i32 @PyCell_Set(ptr, ptr)");
                std::string r = fresh();
                o_ << "  " << r << " = call i32 @PyCell_Set(ptr " << v(in.args[0])
                   << ", ptr " << v(in.args[1]) << ")\n";
                break;
            }
            case Op::IntConst: {
                // A machine int materialised as an i32 the call site widens.
                o_ << "  " << v(*in.result) << " = add i32 0, " << in.text << "\n";
                break;
            }
            case Op::ConstComplex: {
                need("declare ptr @PyComplex_FromDoubles(double, double)");
                std::string re = in.text.substr(0, in.text.find(' '));
                std::string im = in.text.substr(in.text.find(' ') + 1);
                o_ << "  " << v(*in.result)
                   << " = call ptr @PyComplex_FromDoubles(double " << fp(re)
                   << ", double " << fp(im) << ")\n";
                check(in, v(*in.result), true);
                break;
            }
            case Op::Unpack: {
                need("declare ptr @pyc_rt_unpack(ptr, i64)");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_unpack(ptr "
                   << v(in.args[0]) << ", i64 " << in.imm << ")\n";
                check(in, v(*in.result), true);
                break;
            }
            case Op::Raise: {
                need("declare i32 @pyc_rt_raise(ptr)");
                std::string r = fresh();
                o_ << "  " << r << " = call i32 @pyc_rt_raise(ptr "
                   << v(in.args[0]) << ")\n";
                // Always fails, so control always leaves by the error edge.
                o_ << "  br label %bb" << (in.on_error ? *in.on_error : 0) << "\n";
                break;
            }
            case Op::BuildClass: {
                // args: bases, ns, meta, kwds. The last two are null for a
                // plain `class C:` -- PyObject_Call treats a null kwds as no
                // keywords, so no separate path is needed for that case.
                need("declare ptr @pyc_rt_build_class(ptr, ptr, ptr, ptr, ptr)");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_build_class(ptr "
                   << cstr(in.text) << ", ptr " << v(in.args[0])
                   << ", ptr " << v(in.args[1])
                   << ", ptr " << v(in.args[2])
                   << ", ptr " << v(in.args[3]) << ")\n";
                check(in, v(*in.result), true);
                break;
            }
            case Op::ImportModule: {
                if (in.imm) {
                    // __import__(name, NULL, NULL, NULL, 0) returns the
                    // top-level package, which is what `import a.b` binds.
                    need("declare ptr @PyImport_ImportModuleLevel(ptr, ptr, ptr, ptr, i32)");
                    o_ << "  " << v(*in.result)
                       << " = call ptr @PyImport_ImportModuleLevel(ptr " << cstr(in.text)
                       << ", ptr null, ptr null, ptr null, i32 0)\n";
                } else {
                    // Dotted names yield the named module itself here.
                    need("declare ptr @PyImport_ImportModule(ptr)");
                    o_ << "  " << v(*in.result) << " = call ptr @PyImport_ImportModule(ptr "
                       << cstr(in.text) << ")\n";
                }
                check(in, v(*in.result), true);
                break;
            }
            case Op::IterNext: {
                need("declare ptr @PyIter_Next(ptr)");
                need("declare ptr @PyErr_Occurred()");
                o_ << "  " << v(*in.result) << " = call ptr @PyIter_Next(ptr "
                   << v(in.args[0]) << ")\n";
                std::string isnull = fresh(), maybe = "iterend" + std::to_string(tmp_++);
                o_ << "  " << isnull << " = icmp eq ptr " << v(*in.result) << ", null\n";
                o_ << "  br i1 " << isnull << ", label %" << maybe
                   << ", label %bb" << in.target << "\n";
                o_ << maybe << ":\n";
                // NULL means exhausted OR failed; only PyErr_Occurred tells
                // them apart, and conflating them would swallow an exception
                // raised inside __next__.
                std::string err = fresh(), haserr = fresh();
                o_ << "  " << err << " = call ptr @PyErr_Occurred()\n";
                o_ << "  " << haserr << " = icmp ne ptr " << err << ", null\n";
                o_ << "  br i1 " << haserr << ", label %bb"
                   << (in.on_error ? *in.on_error : in.target_else)
                   << ", label %bb" << in.target_else << "\n";
                break;
            }
            case Op::Phi: {
                o_ << "  " << v(*in.result) << " = phi ptr ";
                for (std::size_t i = 0; i < in.args.size(); ++i) {
                    auto it = tail_label_.find(in.phi_blocks[i]);
                    std::string lbl = (it != tail_label_.end()) ? it->second
                                    : ("bb" + std::to_string(in.phi_blocks[i]));
                    o_ << (i ? ", " : "") << "[ " << v(in.args[i]) << ", %" << lbl << " ]";
                }
                o_ << "\n";
                break;
            }
            case Op::MakeFunction: {
                need("declare ptr @pyc_rt_make_function(ptr, ptr, i32, i32, i32, i32, ptr, ptr, ptr, i32, i32, ptr, i32)");
                std::size_t ti = (std::size_t)in.imm;
                bool valid = in.has_imm && ti < m_.functions.size();
                const ir::Function* t = valid ? &m_.functions[ti] : nullptr;
                // The parameter-name table lets the callee bind keywords.
                std::string names = t ? argnames_global(ti) : "null";
                std::string clo = closure_arg(in);      // fills pre_
                o_ << pre_.str(); pre_.str("");
                o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_make_function(ptr "
                   << cstr(in.text) << ", ptr " << (t ? fname(ti) : "null")
                   << ", i32 " << (t ? (int)t->params.size() - t->nkwonly : 0)
                   << ", i32 " << (t ? t->nkwonly : 0)
                   << ", i32 " << (t ? t->nposonly : 0)
                   << ", i32 " << (t ? t->locals.size() : 0)
                   << ", ptr " << names
                   << ", ptr " << (in.args.empty() || !in.args[0].valid()
                                    ? "null" : v(in.args[0]))
                   << ", ptr " << (in.args.size() < 2 || !in.args[1].valid()
                                    ? "null" : v(in.args[1]))
                   << ", i32 " << ((int)in.target - 1)
                   << ", i32 " << ((int)in.target_else - 1)
                   << ", ptr " << clo
                   << ", i32 " << (t ? (int)t->freevars.size() : 0) << ")\n";
                check(in, v(*in.result), true);
                break;
            }
            case Op::Br:
                o_ << "  br label %bb" << in.target << "\n";
                break;
            case Op::CondBr: {
                std::string c = fresh();
                o_ << "  " << c << " = icmp ne i32 " << v(in.args[0]) << ", 0\n";
                o_ << "  br i1 " << c << ", label %bb" << in.target
                   << ", label %bb" << in.target_else << "\n";
                break;
            }
            case Op::Return:
                if (is_main) o_ << "  ret i32 0\n";
                else if (!in.args.empty()) o_ << "  ret ptr " << v(in.args[0]) << "\n";
                else { need("declare ptr @pyc_rt_none()");
                       std::string n = fresh();
                       o_ << "  " << n << " = call ptr @pyc_rt_none()\n";
                       o_ << "  ret ptr " << n << "\n"; }
                break;
            case Op::ReturnErr:
                o_ << (is_main ? "  ret i32 -1\n" : "  ret ptr null\n");
                break;
        }
        (void)f;
    }

    void emit_capi(const ir::Instr& in) {
        bool ptr_ret = (in.result_ownership == Ownership::Owned
                     || in.result_ownership == Ownership::Borrowed
                     || in.result_ownership == Ownership::AlwaysNull);
        const rt::CApiSymbol* sym = rt::lookup(in.text);
        std::string kinds = sym ? std::string(sym->param_kinds) : std::string();
        std::ostringstream sig, call;
        sig << "declare " << (ptr_ret ? "ptr" : "i32") << " @" << in.text << "(";
        call << "  " << v(*in.result) << " = call " << (ptr_ret ? "ptr" : "i32")
             << " @" << in.text << "(";
        // The immediate occupies its true C parameter position, which is what
        // makes the steal indices in §4's table line up with reality.
        std::size_t ai = 0;
        std::size_t total = in.args.size() + (in.has_imm ? 1 : 0);
        for (std::size_t p = 0; p < total; ++p) {
            if (p) { sig << ", "; call << ", "; }
            char k = (p < kinds.size()) ? kinds[p] : 'o';
            if (in.has_imm && (int)p == imm_pos(in, total)) {
                sig << "i64"; call << "i64 " << in.imm;
            } else if (k == 'i') {
                // The IR value is a machine int (i32); widen it to the
                // parameter's width rather than passing a pointer.
                std::string w = fresh();
                pre_ << "  " << w << " = zext i32 " << v(in.args[ai++]) << " to i64\n";
                sig << "i64"; call << "i64 " << w;
            } else {
                sig << "ptr"; call << "ptr " << v(in.args[ai++]);
            }
        }
        sig << ")"; call << ")\n";
        need(sig.str());
        o_ << pre_.str();
        pre_.str("");
        o_ << call.str();
        check(in, v(*in.result), ptr_ret);
    }

    // Lowering does not record imm_pos in the instruction, so recover it:
    // a size argument leads (PyList_New), an index sits at parameter 1
    // (PyList_SetItem), and a compare opid trails (PyObject_RichCompare).
    static int imm_pos(const ir::Instr& in, std::size_t total) {
        if (in.args.empty()) return 0;
        if (in.text == "PyObject_RichCompare") return (int)total - 1;
        return 1;
    }

    // Every alloca goes in the ENTRY block, never where it is used.
    //
    // An alloca inside a loop body is not reclaimed until the function
    // returns, so each iteration took another slice of C stack. Measured: any
    // call in a loop -- `len(b"abc")`, anything -- died with
    //
    //     RecursionError: Stack overflow (used 8148 kB) while calling a
    //     Python object
    //
    // after roughly 500,000 iterations, about 16 bytes a call. A loop with no
    // call in it (`c += 1`) ran forever, which is what localised it to the
    // call's argument array rather than to loops in general. Any long-running
    // compiled program that calls anything in a loop would eventually die.
    //
    // Collected during the discarded first emission pass and written out
    // before bb0 in the second. The passes restore tmp_ between them, so the
    // names they generate are identical and the recorded ones match.
    std::string hoisted_alloca(std::size_t n) {
        std::string name = fresh();
        allocas_.push_back({name, n});
        return name;
    }
    std::vector<std::pair<std::string, std::size_t>> allocas_;

    void emit_call(const ir::Instr& in) {
        need("declare ptr @pyc_rt_call(ptr, ptr, i64)");
        std::size_t n = in.args.size() - 1;
        std::string arr = hoisted_alloca(n ? n : 1);
        for (std::size_t i = 0; i < n; ++i) {
            std::string p = fresh();
            o_ << "  " << p << " = getelementptr [" << (n ? n : 1)
               << " x ptr], ptr " << arr << ", i64 0, i64 " << i << "\n";
            o_ << "  store ptr " << v(in.args[i + 1]) << ", ptr " << p << "\n";
        }
        o_ << "  " << v(*in.result) << " = call ptr @pyc_rt_call(ptr "
           << v(in.args[0]) << ", ptr " << arr << ", i64 " << n << ")\n";
        check(in, v(*in.result), true);
    }

    // Build the closure tuple inline: a small alloca holding the cells this
    // nested function captures, in freevar order.
    // args[0] = defaults, args[1] = kwdefaults, args[2..] = closure cells.
    std::string closure_arg(const ir::Instr& in) {
        std::size_t n = in.args.size() > 2 ? in.args.size() - 2 : 0;
        if (!n) return "null";
        std::string arr = hoisted_alloca(n);
        for (std::size_t i = 0; i < n; ++i) {
            std::string p = fresh();
            pre_ << "  " << p << " = getelementptr [" << n << " x ptr], ptr "
                 << arr << ", i64 0, i64 " << i << "\n";
            pre_ << "  store ptr " << v(in.args[i + 2]) << ", ptr " << p << "\n";
        }
        return arr;
    }

    std::map<std::string, std::string> argnames_;
    std::string argnames_global(std::size_t idx) {
        const ir::Function& f = m_.functions[idx];
        if (f.params.empty()) return "null";
        auto it = argnames_.find(std::to_string(idx));
        if (it != argnames_.end()) return it->second;
        std::string g = "@.args" + std::to_string(idx);
        std::string body = "[" + std::to_string(f.params.size()) + " x ptr] [";
        for (std::size_t i = 0; i < f.params.size(); ++i)
            body += (i ? ", ptr " : "ptr ") + cstr(f.params[i]);
        body += "]";
        argnames_[std::to_string(idx)] = g;
        argname_defs_.push_back(g + " = private unnamed_addr constant " + body);
        return g;
    }
    std::vector<std::string> argname_defs_;
    std::vector<std::string> genexp_caches_;
    int genexp_n_ = 0;
    int tb_n_ = 0;

    void emit_constants() {
        for (const std::string& d : genexp_caches_) o_ << d << "\n";
        for (const std::string& d : argname_defs_) o_ << d << "\n";
        o_ << "\n";
        for (const auto& [text, name] : strs_)
            o_ << name << " = private unnamed_addr constant ["
               << text.size() + 1 << " x i8] c\"" << escape(text) << "\\00\"\n";
    }
    // The table, and the function that fills it. Emitted after every body so
    // the size is known; LLVM does not require a global to be defined before
    // its uses.
    void emit_pyconsts() {
        std::size_t n = pyconst_order_.size() ? pyconst_order_.size() : 1;
        o_ << "\n@.pyconsts = internal global [" << n
           << " x ptr] zeroinitializer\n\n";
        o_ << "define internal i32 @__pyc_init_consts() {\nentry:\n";
        for (std::size_t i = 0; i < pyconst_order_.size(); ++i) {
            const char kind = pyconst_order_[i].first;
            const std::string& text = pyconst_order_[i].second;
            std::string val = "%c" + std::to_string(i);
            std::string ptr = "%p" + std::to_string(i);
            std::string ok = "ok" + std::to_string(i);
            switch (kind) {
                case 's':
                    need("declare ptr @pyc_rt_str(ptr, i64)");
                    o_ << "  " << val << " = call ptr @pyc_rt_str(ptr " << cstr(text)
                       << ", i64 " << text.size() << ")\n";
                    break;
                case 'b':
                    need("declare ptr @pyc_rt_bytes(ptr, i64)");
                    o_ << "  " << val << " = call ptr @pyc_rt_bytes(ptr " << cstr(text)
                       << ", i64 " << text.size() << ")\n";
                    break;
                case 'i':
                    need("declare ptr @pyc_rt_int_from_text(ptr)");
                    o_ << "  " << val << " = call ptr @pyc_rt_int_from_text(ptr "
                       << cstr(text) << ")\n";
                    break;
                default:
                    need("declare ptr @PyFloat_FromDouble(double)");
                    o_ << "  " << val << " = call ptr @PyFloat_FromDouble(double "
                       << fp(text) << ")\n";
                    break;
            }
            std::string isnull = "%n" + std::to_string(i);
            o_ << "  " << isnull << " = icmp eq ptr " << val << ", null\n";
            o_ << "  br i1 " << isnull << ", label %fail, label %" << ok << "\n";
            o_ << ok << ":\n";
            o_ << "  " << ptr << " = getelementptr inbounds ptr, ptr "
               << "@.pyconsts, i64 " << i << "\n";
            o_ << "  store ptr " << val << ", ptr " << ptr << "\n";
        }
        o_ << "  ret i32 0\nfail:\n  ret i32 -1\n}\n";
    }

    void emit_declarations() {
        o_ << "\n";
        for (const std::string& d : decls_) o_ << d << "\n";
    }
};

}  // namespace

std::string codegen_llvm(const ir::Module& m) { return Codegen(m).run(); }

}  // namespace pyc
