#!/usr/bin/env python3
"""Generate the typed C++ AST from a schema (INTERFACES.md §2.2).

    ./compiler/tools/gen_ast.py schema.json -o compiler/include/pyc/ast/generated.hpp

GENERATED CODE. Never hand-edit the output: regenerate it. That is what makes
CHARTER I4 work -- when CPython adds a node kind, the regenerated variant gains
an alternative and every non-exhaustive std::visit stops compiling.
"""

from __future__ import annotations

import argparse
import json
import sys

SCALARS = {"str": "std::string", "int": "std::int64_t", "bool": "bool"}

# ASDL names are not chosen with C++ in mind: the sum type `operator` is a
# keyword. Mangle systematically rather than special-casing, so a future
# CPython adding e.g. `class` or `template` does not silently break the build.
_CXX_KEYWORDS = {
    "alignas", "alignof", "and", "and_eq", "asm", "auto", "bitand", "bitor",
    "bool", "break", "case", "catch", "char", "class", "compl", "concept",
    "const", "consteval", "constexpr", "constinit", "const_cast", "continue",
    "co_await", "co_return", "co_yield", "decltype", "default", "delete",
    "do", "double", "dynamic_cast", "else", "enum", "explicit", "export",
    "extern", "false", "float", "for", "friend", "goto", "if", "inline",
    "int", "long", "mutable", "namespace", "new", "noexcept", "not", "not_eq",
    "nullptr", "operator", "or", "or_eq", "private", "protected", "public",
    "register", "reinterpret_cast", "requires", "return", "short", "signed",
    "sizeof", "static", "static_assert", "static_cast", "struct", "switch",
    "template", "this", "thread_local", "throw", "true", "try", "typedef",
    "typeid", "typename", "union", "unsigned", "using", "virtual", "void",
    "volatile", "wchar_t", "while", "xor", "xor_eq",
}


def cxx(name: str) -> str:
    """Python/ASDL identifier -> a legal C++ one."""
    return name + "_" if name in _CXX_KEYWORDS else name


def cpp_type(f: dict, sums: set[str], trivial: set[str], nodes: set[str]) -> str:
    t, q = f["type"], f["quant"]
    if t == "constant":                     # a Python literal
        return "ConstantValue"
    if t == "object":
        raise SystemExit(
            f"gen_ast: field of untyped `object` is not resolved. Add it to "
            f"_OBJECT_FIELDS in extract_schema.py with its real type -- "
            f"guessing produced silently broken t-strings and `case None:`.")
    if t in SCALARS:
        base = SCALARS[t]
        return {"one": base, "opt": f"std::optional<{base}>",
                "seq": f"std::vector<{base}>"}[q]
    if t in trivial:                        # field-free sum: no indirection
        c = "::pyc::ast::" + cxx(t)
        return {"one": c, "opt": f"std::optional<{c}>",
                "seq": f"std::vector<{c}>"}[q]
    if t in sums or t in nodes:             # recursive: needs a Box
        c = "::pyc::ast::" + cxx(t)
        if q == "seq" and f.get("nullable_elements"):
            # CPython stores None inside these lists (Dict.keys for `**`,
            # arguments.kw_defaults for a kwonly arg with no default), which
            # _field_types does not express. See extract_schema._NULLABLE_ELEMENTS.
            return f"std::vector<std::optional<Box<{c}>>>"
        return {"one": f"Box<{c}>", "opt": f"std::optional<Box<{c}>>",
                "seq": f"std::vector<{c}>"}[q]
    raise SystemExit(f"gen_ast: unmapped field type {t!r} (quant {q})")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("schema")
    ap.add_argument("-o", "--out", default="-")
    ap.add_argument("--from-json-out", default=None,
                    help="also emit the generated deserializer here")
    ap.add_argument("--walk-out", default=None,
                    help="also emit the generated walker here")
    args = ap.parse_args()

    s = json.load(open(args.schema))
    sums, trivial = set(s["sums"]), set(s["trivial_sums"])
    nodes = set(s["nodes"])
    if s.get("degraded"):
        print("gen_ast: schema is DEGRADED (no _field_types); field types are "
              "unknown. Extract from a 3.13+ interpreter or Python.asdl.",
              file=sys.stderr)
        return 2

    o: list[str] = []
    w = o.append
    w("#pragma once")
    w("// GENERATED by compiler/tools/gen_ast.py -- DO NOT EDIT.")
    w(f"// Source: CPython {s['python_version']} (schema v{s['schema_version']})")
    w("//")
    w("// Regenerate when the target CPython changes. A new node kind will")
    w("// break every non-exhaustive std::visit, which is CHARTER I4 working")
    w("// as designed -- fix the arms, never add a generic `auto` fallback.")
    w('#include "pyc/ast/support.hpp"')
    w("")
    w("namespace pyc::ast {")
    w("")
    w(f"inline constexpr const char* kTargetPython = \"{s['python_version']}\";")
    w("")

    # 1. forward declarations: every sum wrapper and every node.
    w("// --- forward declarations ---")
    for name in sorted(sums | nodes):
        w(f"struct {cxx(name)};")
    w("")

    # 2. trivial sums first: field-free, so they are complete immediately and
    #    can be held by value (keeps `ctx` on every Name allocation-free).
    w("// --- field-free sums (held by value) ---")
    for sname in sorted(trivial):
        for ctor in s["sums"][sname]:
            w(f"struct {cxx(ctor)} {{}};")
        alts = ", ".join(cxx(c) for c in s["sums"][sname])
        w(f"struct {cxx(sname)} {{ std::variant<{alts}> v; }};")
    w("")

    # 3. concrete node structs.
    w("// --- nodes ---")
    for name, info in s["nodes"].items():
        if any(name in s["sums"].get(t, []) for t in trivial):
            continue                       # already emitted above
        w(f"struct {cxx(name)} {{")
        for f in info["fields"]:
            w(f"    {cpp_type(f, sums, trivial, nodes)} {cxx(f['name'])};")
        if info["attributes"]:
            w("    SourceLoc loc;")
        w("};")
    w("")

    # 4. non-trivial sum wrappers, after their constructors are complete.
    w("// --- sums ---")
    for sname, ctors in s["sums"].items():
        if sname in trivial:
            continue
        alts = ",\n                 ".join(cxx(c) for c in ctors)
        w(f"struct {cxx(sname)} {{")
        w(f"    std::variant<{alts}> v;")
        w("};")
    w("")
    w("}  // namespace pyc::ast")
    text = "\n".join(o) + "\n"

    if args.out == "-":
        sys.stdout.write(text)
    else:
        open(args.out, "w").write(text)
        n_ctor = sum(len(v) for v in s["sums"].values())
        print(f"generated {len(s['nodes'])} nodes / {len(s['sums'])} sums "
              f"({n_ctor} constructors) -> {args.out}")
    if args.from_json_out:
        open(args.from_json_out, "w").write(gen_from_json(s))
        print(f"generated deserializer -> {args.from_json_out}")
    if args.walk_out:
        open(args.walk_out, "w").write(gen_walk(s))
        print(f"generated walker -> {args.walk_out}")
    return 0




# ---------------------------------------------------------------------------
# Deserializer generation.
#
# Hand-writing 117 builders would be exactly the hand-maintenance I4 bans: a
# node kind added upstream must not require a human to remember this file.
# ---------------------------------------------------------------------------

def gen_from_json(s: dict) -> str:
    sums, trivial = set(s["sums"]), set(s["trivial_sums"])
    nodes = set(s["nodes"])
    o: list[str] = []
    w = o.append

    w("#pragma once")
    w("// GENERATED by compiler/tools/gen_ast.py -- DO NOT EDIT.")
    w(f"// Source: CPython {s['python_version']}")
    w("//")
    w("// Depth is bounded and reported as a diagnostic (INTERFACES.md §1.2):")
    w("// a stack overflow is an uncontrollable crash and cannot be reported,")
    w("// which would violate I1 at the very first layer.")
    w('#include "pyc/ast/generated.hpp"')
    w('#include "pyc/ast/from_json_support.hpp"')
    w("")
    w("namespace pyc::ast {")
    w("")

    all_types = sorted((sums | nodes) - trivial)
    w("// forward declarations (the grammar is mutually recursive)")
    for t in all_types:
        w(f"bool from_json({cxx(t)}& out, const JsonCtx& c, const json::Value& v, Depth d);")
    for t in sorted(trivial):
        w(f"bool from_json({cxx(t)}& out, const JsonCtx& c, const json::Value& v, Depth d);")
    w("")

    # trivial sums: an object carrying only _kind
    for sname in sorted(trivial):
        w(f"inline bool from_json({cxx(sname)}& out, const JsonCtx& c, "
          f"const json::Value& v, Depth d) {{")
        w("    (void)d;")
        w(f'    std::string_view k; if (!kind_of(c, v, k)) return false;')
        for ctor in s["sums"][sname]:
            w(f'    if (k == "{ctor}") {{ out.v = {cxx(ctor)}{{}}; return true; }}')
        w(f'    return c.unknown_kind(k, "{sname}");')
        w("}")
    w("")

    # concrete nodes
    for name, info in s["nodes"].items():
        if any(name in s["sums"].get(t, []) for t in trivial):
            continue
        w(f"inline bool from_json({cxx(name)}& out, const JsonCtx& c, "
          f"const json::Value& v, Depth d) {{")
        w("    if (!d.ok(c)) return false;")
        for f in info["fields"]:
            fn, ft, q = f["name"], f["type"], f["quant"]
            acc = f'c.doc.find(v, "{fn}")'
            dst = f"out.{cxx(fn)}"
            if ft == "constant":
                w(f"    if (!const_from_json({dst}, c, {acc})) return false;")
            elif ft in SCALARS:
                fn_name = {"str": "str", "int": "i64", "bool": "boolean"}[ft]
                w(f"    if (!{fn_name}_{q}({dst}, c, {acc})) return false;")
            else:
                helper = "node_seq_opt" if (q == "seq" and f.get("nullable_elements")) \
                    else f"node_{q}"
                w(f"    if (!{helper}({dst}, c, {acc}, d.next())) return false;")
        if info["attributes"]:
            w(f"    loc_from_json(out.loc, c, v);")
        w("    return true;")
        w("}")
    w("")

    # non-trivial sums: dispatch on _kind
    for sname, ctors in s["sums"].items():
        if sname in trivial:
            continue
        w(f"inline bool from_json({cxx(sname)}& out, const JsonCtx& c, "
          f"const json::Value& v, Depth d) {{")
        w("    if (!d.ok(c)) return false;")
        w("    std::string_view k; if (!kind_of(c, v, k)) return false;")
        for ctor in ctors:
            w(f'    if (k == "{ctor}") {{ {cxx(ctor)} n; '
              f"if (!from_json(n, c, v, d)) return false; "
              f"out.v = std::move(n); return true; }}")
        w(f'    return c.unknown_kind(k, "{sname}");')
        w("}")
    w("")
    w("}  // namespace pyc::ast")
    return "\n".join(o) + "\n"

# ---------------------------------------------------------------------------
# Walker generation. Generated for the same reason as the deserializer: a
# hand-written exhaustive visitor over 117 node types is precisely the
# hand-maintenance I4 exists to eliminate.
# ---------------------------------------------------------------------------

def gen_walk(s: dict) -> str:
    sums, trivial = set(s["sums"]), set(s["trivial_sums"])
    nodes = set(s["nodes"])
    o: list[str] = []
    w = o.append
    w("#pragma once")
    w("// GENERATED by compiler/tools/gen_ast.py -- DO NOT EDIT.")
    w('#include "pyc/ast/generated.hpp"')
    w("")
    w("#include <string_view>")
    w("")
    w("namespace pyc::ast {")
    w("")
    w("struct WalkSink { virtual ~WalkSink() = default;")
    w("                  virtual void on(std::string_view kind) = 0; };")
    w("")
    for t in sorted((sums | nodes) - trivial):
        w(f"void walk(const {cxx(t)}& n, WalkSink& s);")
    w("")
    for name, info in s["nodes"].items():
        if any(name in s["sums"].get(t, []) for t in trivial):
            continue
        w(f"inline void walk(const {cxx(name)}& n, WalkSink& s) {{")
        w(f'    s.on("{name}");')
        for f in info["fields"]:
            t, q, fn = f["type"], f["quant"], cxx(f["name"])
            if t in SCALARS or t in ("object", "constant") or t in trivial:
                continue
            if q == "one":
                w(f"    if (n.{fn}) walk(*n.{fn}, s);")
            elif q == "opt":
                w(f"    if (n.{fn} && *n.{fn}) walk(**n.{fn}, s);")
            elif f.get("nullable_elements"):
                w(f"    for (const auto& x : n.{fn}) if (x && *x) walk(**x, s);")
            else:
                w(f"    for (const auto& x : n.{fn}) walk(x, s);")
        w("}")
    w("")
    for sname, ctors in s["sums"].items():
        if sname in trivial:
            continue
        w(f"inline void walk(const {cxx(sname)}& n, WalkSink& s) {{")
        w("    std::visit(ov{")
        for c in ctors:
            w(f"        [&](const {cxx(c)}& x) {{ walk(x, s); }},")
        w("    }, n.v);")
        w("}")
    w("")
    w("}  // namespace pyc::ast")
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    sys.exit(main())
